#ifndef __V300DATA_H__
#define __V300DATA_H__

//////////////////////////////////////////////////////////////////
//
// Revision information
//
//
//
// March 19 2002: ewcpahi:
//			Added states for YP, MCIDM, VVM and ACS
//			Added signals to SLIST_TAG_XC_RX and SLIST_TAG_YP_TX
// March 9-10 2002: Added Event data
// March 6 2002: Redefinition of States to same structure as Signals
// March 5 2002: Extensive update of Signals with compare towards 3.0
//
//////////////////////////////////////////////////////////////////

#include "PString.h"
#include "DecodeDataDefs.h"


char *NameV300 = "WebSwitch 2000 rel 3.0";
int   Ver300 = 300;


char *SignalsV300[] =  {
// 0
		TAG_ATTRIBUTE"SLIST_TAG_WD_AGENT",
// 1
		TAG_ATTRIBUTE"SLIST_TAG_WD_MANAGER",
// 2		
		TAG_ATTRIBUTE"SLIST_TAG_TEST",
// 3		
		TAG_ATTRIBUTE"SLIST_TAG_QSLAC",
			"QSLAC_OFFHOOK_Signal",
			"QSLAC_ONHOOK_Signal",
			"QSLAC_LINE_REVERSAL_Signal",
// 4		
		TAG_ATTRIBUTE"SLIST_TAG_DSP",
			"DSP_DTMF_DETECT_Signal",
			"DSP_BANKSWITCH_Signal",
			"DSP_TONE_DETECT_Signal",
			"DSP_CID_DETECT_Signal",
			"DSP_TONE_SENT_Signal",
			"DSP_CID_SENT_Signal",
			"DSP_DT_AS_SENT_Signal",
			"DSP_VMWI_SENT_Signal",
// 5
		TAG_ATTRIBUTE"SLIST_TAG_EXT_DRV",
			"EXTDR_FLASH_PEND_TIMER_Signal",
			"EXTDR_RING_TIMER_Signal",
			"EXTDR_RING_DEACTIVATE_Signal",
			"EXTDR_RING_FILTER_Signal",
			"EXTDR_DISCONNECT_TIMER_Signal",
			"EXTDR_CID_AS_TIMER_Signal",
			"EXTDR_VMWI_TIMER_Signal",
			"EXTDR_VMWI_REFRESH_TIMER_Signal",
			"EXTDR_EXT_ALERT_REQ_Signal",
			"EXTDR_EXT_RELEASE_REQ_Signal",
			"EXTDR_EXT_DIGIT_COL_ON_Signal",
			"EXTDR_EXT_DIGIT_COL_OFF_Signal",
			"EXTDR_EXT_SEND_TONE_Signal",
			"EXTDR_EXT_DISCONNECT_REQ_Signal",
			"EXTDR_EXT_CLEAR_CONNECTION_Signal",
			"EXTDR_EXT_SPECIFIC_Signal",
			"EXTDR_EXT_ANSWER_REQ_Signal",
			"EXTDR_EXT_CALL_PROC_REQ_Signal",
			"EXTDR_EXT_ALERT_RSP_REQ_Signal",
			"EXTDR_EXT_UPDATE_VMWI_Signal",
// 6
		TAG_ATTRIBUTE"SLIST_TAG_EXT_DRV_TX",
			"EXTDR_OFFHOOK_IND_Signal",
			"EXTDR_ONHOOK_IND_Signal",
			"EXTDR_FLASH_KEY_IND_Signal",
			"EXTDR_ERR_IND_Signal",
			"EXTDR_RING_IND_Signal",
			"EXTDR_DIGIT_RECEIVED_IND_Signal",
			"EXTDR_MAKE_CALL_IND_Signal",
			"EXTDR_ANSWER_CNF_Signal",
			"EXTDR_CALL_PROC_CNF_Signal",
			"EXTDR_DIGIT_COLL_CNF_Signal",
			"EXTDR_ALERT_RSP_CNF_Signal",
			"EXTDR_CTI_LOGON_Signal",
			"EXTDR_CTI_LOGOFF_Signal",
// 7
       TAG_ATTRIBUTE"SLIST_TAG_TR_DRV",
			"TRDR_DIALTONE_TIMER_Signal",
			"TRDR_HANGUP_TIMER_Signal",
			"TRDR_ONHOOK_TIMER_Signal",
			"TRDR_OFFHOOK_TIMER_Signal",
			"TRDR_RING_FILTER_TIMER_Signal",
			"TRDR_SECOND_RING_TIMER_Signal",
			"TRDR_RINGON_GUARD_TIMER_Signal",
			"TRDR_POLARITY_FILTER_TIMER_Signal",
			"TRDR_POL_PEND_TIMER_Signal",
			"TRDR_VOLTAGE_TIMER_Signal",
			"TRDR_FLASH_TIMER_Signal",
			"TRDR_DIGIT_SENT_Signal",
			"TRDR_RING_ON_DETECT_Signal",
			"TRDR_RING_OFF_DETECT_Signal",
// 8
       TAG_ATTRIBUTE"SLIST_TAG_TR_DRV_TX",
			"TRDR_ERROR_IND_Signal",
			"TRDR_ERROR_CLEARED_IND_Signal",
			"TRDR_CALL_IND_Signal",
			"TRDR_INFO_IND_Signal",
			"TRDR_CALL_CNF_Signal",
			"TRDR_CALL_PROC_IND_Signal",
			"TRDR_ALERT_IND_Signal",
			"TRDR_ANSWER_IND_Signal",
			"TRDR_DISCONNECT_IND_Signal",
			"TRDR_RELEASE_IND_Signal",
			"TRDR_RELEASE_CNF_Signal",
			"TRDR_FLASH_CNF_Signal",
			"TRDR_PROGRESS_IND_Signal",
			"TRDR_ANSWER_CNF_Signal",
			"TRDR_START_DIGIT_COL_CNF_Signal",
			"TRDR_STOP_DIGIT_COL_CNF_Signal",
			"TRDR_TRANSIT_INFO_Signal",        // 16  Transit data to send to the other side
			"TRDR_SERVICE_RSP_Signal",         // 17  Response to a service request
			"TRDR_CALL_PROC_CNF_Signal",       // 18  Response to a Call Proceed Request
// 9
       TAG_ATTRIBUTE"SLIST_TAG_SES",
			"SESM_START_SESM_Signal",
// 10
       TAG_ATTRIBUTE"SLIST_TAG_SES_TSP_TX",
			"SESM_START_TSP_Signal",
			"SESM_START_CONF_Signal",
// 11
       TAG_ATTRIBUTE"SLIST_TAG_SES_WBS_TX",
			"SESM_WSCTL_CON_REQ_Signal",
			"SESM_WSCTL_CON_IND_Signal",
// 12
       TAG_ATTRIBUTE"SLIST_TAG_SES_CFG_TX",
// 13
       TAG_ATTRIBUTE"SLIST_TAG_SES_XC_TX",
// 14
       TAG_ATTRIBUTE"SLIST_TAG_WSUT",
// 15
       TAG_ATTRIBUTE"SLIST_TAG_WSCTL",
// 16
       TAG_ATTRIBUTE"SLIST_TAG_WBS_TX",
// 17
       TAG_ATTRIBUTE"SLIST_TAG_WSUT_TX",
// 18
       TAG_ATTRIBUTE"SLIST_TAG_WSRX_TX",
// 19
       TAG_ATTRIBUTE"SLIST_TAG_EXT",
			"EXT_TIMER_TIMER_Signal",
			"EXT_TIMER_START_DIGIT_TIMEOUT_Signal",
			"EXT_TIMER_INTER_DIGIT_TIMEOUT_Signal",
			"EXT_RECALL_TIMER_Signal",
// 20
       TAG_ATTRIBUTE"SLIST_TAG_CM",
			"CM_TIMER_TIMER_Signal",
			"CM_XC_CALLBACK_Signal",
			"CM_XFER_REQ_Signal",
			"CM_ACQUIRE_CALL_Signal",
			"CM_PARK_DISCONNECT_Signal",
			"CM_PICKUP_IND_Signal",
			"CM_PROVIDE_MUSIC_Signal",
			"CM_REMOVE_MUSIC_REQ_Signal",
			"CM_REMOVE_MUSIC_RSP_Signal",
			"CM_ACQUIRE_CALL_CNF_Signal",
			"CM_RECALL_Signal",	
			"CM_DEFLECT_CALL_REQ_Signal",
			"CM_PICKUP_CNF_Signal",
			"CM_PICKUP_REJECT_Signal",
			"CM_CONFERENCE_REQ_Signal",
			"CM_CONFERENCE_RSP_Signal",
			"CM_CONN_REQ_CNF_Signal",
			"CM_REROUTE_IND_Signal",
			"CM_TAG_ASSOCIATED_DATA_Signal",
			"CM_CAB_ACTIVATE_REQUEST_Signal",
			"CM_CAB_FREE_NOTIFICATION_Signal",
			"CM_CAB_CANCELATION_Signal",
			"CM_CAB_ACTIVATE_RESPONSE_Signal",
			"CM_CAB_SUSPEND_Signal",
			"CM_CAB_RESUME_Signal",
			"CM_REPORT_TRANSFER_Signal",
			"CM_REROUTE_CALL_Signal",
			"CM_INTERNAL_DATA_IND_Signal",
			"CM_INTERNAL_DATA_RSP_Signal",
			"CM_SEND_DIGITS_CNF_Signal",
			"CM_CONF_TO_REGULAR_REPLACE_CALLID_Signal",
			"CM_CONF_TO_REGULAR_REPLACE_CALLID_RSP_Signal",
// 21
       TAG_ATTRIBUTE"SLIST_TAG_CM_TX",
			"CM_ALERTING_RSP_Signal",
			"CM_CALL_ANSWERED_Signal",
			"CM_CALL_PROCEEDING_Signal",
			"CM_CONNECT_REQ_Signal",
			"CM_CONNECT_CONFIRMED_Signal",
			"CM_DISCONNECT_REQ_Signal",
			"CM_FLASH_REQ_Signal",
			"CM_RELEASE_REQ_Signal",
			"CM_RELEASE_COMPLETE_REQ_Signal",
			"CM_SEND_DIGITS_Signal",
			"CM_START_DIGIT_COLLECT_Signal",
			"CM_STOP_DIGIT_COLLECT_Signal",
			"CM_PROGRESS_REQ_Signal",
			"CM_FLASH_RSP_Signal",
			"CM_REPLACE_CALLID_Signal",
			"CM_REQUEST_RESERVE_Signal",
			"CM_REPLACE_FSM_Signal",
			"CM_NUMBER_COMPLETE_Signal",
			"CM_CAB_FREE_NOT_REQ_Signal",
			"CM_CABREQUEST_RSP_Signal",
			"CM_CABRESUME_Signal",
// 22
       TAG_ATTRIBUTE"SLIST_TAG_TSP",
			"TSPM_START_TSP_Signal",
// 23
       TAG_ATTRIBUTE"SLIST_TAG_TSP_SES_TX",
// 24
       TAG_ATTRIBUTE"SLIST_TAG_TSP_EXT_TX",
			"TSP_EXT_MAKECALL_Signal",
			"TSP_EXT_HANGUP_Signal",
			"TSP_EXT_DETACH_Signal",
			"TSP_EXT_HOLD_Signal",
			"TSP_EXT_CANCEL_HOLD_Signal",
			"TSP_EXT_TRANSFER_Signal",
			"TSP_EXT_FORWARD_Signal",
			"TSP_EXT_CANCEL_FORWARD_Signal",
			"TSP_EXT_PICKUP_Signal",
			"TSP_EXT_CONFERENCE_Signal",
			"TSP_EXT_CONSULT_Signal",
			"TSP_EXT_CANCEL_CONSULT_Signal",
			"TSP_EXT_STATUS_Signal",
			"TSP_EXT_VVMPACKET_Signal",
			"TSP_EXT_DIALSEQ_Signal",
			"TSP_EXT_FLASH_Signal",
			"TSP_EXT_ATTACH_REQUEST_Signal",
// 25
       TAG_ATTRIBUTE"SLIST_TAG_CFG",
			"CFG_SET_ATTRIBUTE_Signal",
// 26
       TAG_ATTRIBUTE"SLIST_TAG_CFG_TX",
// 27
       TAG_ATTRIBUTE"SLIST_TAG_EXT_TX",
// 28
       TAG_ATTRIBUTE"SLIST_TAG_EXT_TSP_TX",
			"EXT_TSP_CALL_REQUEST_STATUS_Signal",
			"EXT_TSP_RING_Signal",
			"EXT_TSP_CALL_REQUEST_CONFIRM_Signal",
			"EXT_TSP_REMOTE_HANGUP_Signal",
			"EXT_TSP_LOCAL_HANGUP_Signal",
			"EXT_TSP_ALERT_REQUEST_Signal",
			"EXT_TSP_CALL_ACTIVE_Signal",
			"EXT_TSP_ATTACH_CONFIRM_Signal",
			"EXT_TSP_OFFHOOK_Signal",
			"EXT_TSP_HOLD_Signal",
			"EXT_TSP_CANCEL_HOLD_Signal",
			"EXT_TSP_TRANSFER_Signal",
			"EXT_TSP_FORWARD_Signal",
			"EXT_TSP_CANCEL_FORWARD_Signal",
			"EXT_TSP_PICKUP_Signal",
			"EXT_TSP_CONFERENCE_Signal",
			"EXT_TSP_CONSULT_Signal",
			"EXT_TSP_CANCEL_CONSULT_Signal",
			"EXT_TSP_REPORT_STATUS_Signal",
			"EXT_TSP_VVMPACKET_Signal",
			"EXT_TSP_DIALSEQ_Signal",
			"EXT_TSP_FLASH_CONF_Signal",
			"EXT_TSP_ATTACH_REJ_Signal",
// 29
       TAG_ATTRIBUTE"SLIST_TAG_WSDRV",
// 30
       TAG_ATTRIBUTE"SLIST_TAG_WSDRV_TX",
// 31
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK",
// 32
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_CM_TX",
// 33
       TAG_ATTRIBUTE"SLIST_TAG_VM",
			"VM_RECORD_LIMIT_TIMER_Signal",
			"VM_INTER_DIGIT_DELAY_TIMER_Signal",
			"VM_NO_ACTIVITY_TIMER_Signal",
			"VM_PLAY_MESSAGE_Signal",
			"VM_SEND_MSG_COUNT_Signal",
			"VM_TEST_Signal",
			"VM_DONE_STREAMING_Signal",
// 34
       TAG_ATTRIBUTE"SLIST_TAG_VM_CM",
			"VM_CM_DIGITSTOP_IND_Signal",
			"VM_CM_INSPEECHDIGITS_IND_Signal",
			"VM_CM_REROUTE_IND_Signal",
			"VM_CM_XFER_RESTART_CNF_Signal",
// 35
       TAG_ATTRIBUTE"SLIST_TAG_VSCTL",
			"VSCTL_PLAYBACK_TIMER_Signal",
			"VSCTL_PLAYBACK_REFILL_Signal",
			"VSCTL_RECORD_TIMER_Signal",
			"VSCTL_RECORD_FLUSH_TIMER_Signal",
			"VSCTL_CLOSE_SESSION_Signal",
			"VSCTL_CLOSE_FILE_Signal",
			"VSCTL_CREATE_FILE_Signal",
			"VSCTL_DELETE_FILE_Signal",
// 36
       TAG_ATTRIBUTE"SLIST_TAG_PHR",
			"PHR_TIMER_TIMER_Signal",
			"PHR_DONE_PLAYING_Signal",
			"PHR_XC_CALLBACK_Signal",
// 37
       TAG_ATTRIBUTE"SLIST_TAG_PHR_TX",
			"PHR_DONE_STREAMING_Signal",
			"PHR_DONE_STREAMING_MSG_Signal",
			"PHR_START_SESSION_Signal",
			"PHR_CLOSE_SESSION_Signal",
// 38
       TAG_ATTRIBUTE"SLIST_TAG_XC_SES_TX",
// 39
       TAG_ATTRIBUTE"SLIST_TAG_XC_WBS_TX",
// 40
       TAG_ATTRIBUTE"SLIST_TAG_HB",
			"WSHB_HEART_BEAT_Signal",
// 41
       TAG_ATTRIBUTE"SLIST_TAG_HB_TX",
// 42
       TAG_ATTRIBUTE"SLIST_TAG_DTP",
			"DTP_CA_TIMER_Signal",
// 43
       TAG_ATTRIBUTE"SLIST_TAG_DTP_RX",
			"DTP_DATA_REQ_Signal",
// 44
       TAG_ATTRIBUTE"SLIST_TAG_DCM",
			"DCM_TIMER_TIMER_Signal",
// 45
       TAG_ATTRIBUTE"SLIST_TAG_DCM_TX",
			"DCM_DTP_DATA_REQ_Signal",
// 46
       TAG_ATTRIBUTE"SLIST_TAG_DTPUT",
			"DTPUT_START_DTPUT_Signal",
// 47
       TAG_ATTRIBUTE"SLIST_TAG_DTPUT_TX",
			"DTPUT_SWITCH_DOWN_Signal",
// 48
       TAG_ATTRIBUTE"SLIST_TAG_CLOG",
// 49
       TAG_ATTRIBUTE"SLIST_TAG_CLOG_CMON_TX",
			"CLOG_CMON_LAST_POINTER_Signal",
			"CLOG_CMON_UAENTRY_BUF_Signal",
			"CLOG_CMON_NO_UAENTRY_Signal",
// 50
       TAG_ATTRIBUTE"SLIST_TAG_XC",
			"XC_VPM_TONE_IND_Signal",
			"XC_MM_RSP_IND_Signal",
// 51
       TAG_ATTRIBUTE"SLIST_TAG_XC_TX",
// 52
       TAG_ATTRIBUTE"SLIST_TAG_XC_RX",
			"XC_DTP_DATA_IND_Signal",
			"XC_DTP_SWITCH_DOWN_Signal",
			"XC_DTP_SWITCH_UP_Signal",
// 53
       TAG_ATTRIBUTE"SLIST_TAG_YP",
			"YP_TIMER_TIMER_Signal",
// 54
       TAG_ATTRIBUTE"SLIST_TAG_YP_TX",
			"YP_DTP_DATA_IND_Signal",
			"YP_DTP_SWITCH_DOWN_Signal",
			"YP_DTP_SWITCH_UP_Signal",
// 55
       TAG_ATTRIBUTE"SLIST_TAG_YP_RX",
// 56
       TAG_ATTRIBUTE"SLIST_TAG_DTP_DCM_TX",
			"DCM_DTP_DATA_IND_Signal",
			"DCM_DTP_SWITCH_DOWN_Signal",
			"DCM_DTP_SWITCH_UP_Signal",
// 57
       TAG_ATTRIBUTE"SLIST_TAG_CM_RX",
// 58
       TAG_ATTRIBUTE"SLIST_TAG_CM_TRUNK_TX",
// 59
       TAG_ATTRIBUTE"SLIST_TAG_VVM",
			"VVM_TIMER_TIMER_Signal",
// 60
       TAG_ATTRIBUTE"SLIST_TAG_VVM_TX",
			"VVM_VM_PLAY_REQUEST_Signal",
			"VVM_VM_DELETE_REQUEST_Signal",
			"VVM_VM_STOP_REQUEST_Signal",
// 61
       TAG_ATTRIBUTE"SLIST_TAG_VPDRV",
			"VPDRV_NEW_CMD_Signal",
			"VPDRV_CMD_SENT_Signal",
			"VPDRV_REG_MSG_PEND_Signal",
			"VPDRV_SIG_MSG_PEND_Signal",
			"VPDRV_DTMF_Ch0_Timer_Signal",
			"VPDRV_DTMF_Ch1_Timer_Signal",
			"VPDRV_DTMF_Ch2_Timer_Signal",
			"VPDRV_DTMF_Ch3_Timer_Signal",
			"VPDRV_ToneGen_Ch0_Timer_Signal",
			"VPDRV_ToneGen_Ch1_Timer_Signal",
			"VPDRV_ToneGen_Ch2_Timer_Signal",
			"VPDRV_ToneGen_Ch3_Timer_Signal",
// 62
       TAG_ATTRIBUTE"SLIST_TAG_CM_VM_TX",
			"CM_VM_XFER_RESTART_REQ_Signal",
// 63
       TAG_ATTRIBUTE"SLIST_TAG_H323",
			"H323_seliSelect_Signal",
// 64
       TAG_ATTRIBUTE"SLIST_TAG_H323_TX",
			"IPDRV_RX_SAL_CALL_IND_Signal",
			"IPDRV_RX_SAL_RINGBACK_IND_Signal",
			"IPDRV_RX_SAL_CONNECTED_IND_Signal",
			"IPDRV_RX_SAL_USER_SIGNAL_IND_Signal",
			"IPDRV_RX_SAL_CHECK_CALL_IND_Signal",
			"IPDRV_RX_SAL_DISCONNECTED_IND_Signal",
			"IPDRV_RX_SAL_ERROR_IND_Signal",
			"IPDRV_RX_SAL_MEDIA_UPDATE_Signal",
// 65
       TAG_ATTRIBUTE"SLIST_TAG_H323_RX",
			"IPDRV_TX_SAL_CALL_REQ_Signal",
			"IPDRV_TX_SAL_USER_SIGNAL_REQ_Signal",
			"IPDRV_TX_SAL_CHECK_CALL_REQ_Signal",
			"IPDRV_TX_SAL_DISCONNECT_REQ_Signal",
			"IPDRV_TX_SAL_GK_REGISTER_Signal",
			"IPDRV_TX_SAL_GK_UNREGISTER_Signal",
			"IPDRV_TX_SAL_SET_IP_ADDRESS_Signal",
			"IPDRV_TX_SAL_CONNECT_REQ_Signal",
			"IPDRV_TX_SAL_ALERT_REQ_Signal",
			"IPDRV_TX_SAL_MEDIA_UPDATE_Signal",
// 66
       TAG_ATTRIBUTE"SLIST_TAG_HDRV",
			"HDRV_RING_TIMER_Signal",
			"HDRV_DISCONNECT_TIMER_Signal",
			"HDRV_CALL_CHECK_Signal",
			"HDRV_CALL_MAX_RESPONSE_TIME_Signal",
			"HDRV_VPM_DTMF_Sent_Signal",
			"HDRV_VPM_DTMF_Detected_Signal",
			"HEXT_ALERT_REQ_Signal",
			"HEXT_RELEASE_REQ_Signal",
			"HEXT_DIGIT_COL_ON_Signal",
			"HEXT_DIGIT_COL_OFF_Signal",
			"HEXT_SEND_TONE_Signal",
			"HEXT_DISCONNECT_REQ_Signal",
			"HEXT_SPECIFIC_Signal",
			"HEXT_ANSWER_REQ_Signal",
			"HEXT_CALL_PROC_REQ_Signal",
			"HEXT_ALERT_RSP_REQ_Signal",
			"HEXT_SET_ID_REQ_Signal",
// 67
       TAG_ATTRIBUTE"SLIST_TAG_HDRV_TX",
// 68
       TAG_ATTRIBUTE"SLIST_TAG_ACS",
			"ACS_TIMER_COMMON_TIMER_Signal",
			"ACS_TIMER_POSITION_TIMER_Signal",
			"ACS_TIMER_COMFORT_MSG_TIMER_Signal",
			"ACS_TIMER_FILE_TIMER_Signal",
// 69
       TAG_ATTRIBUTE"SLIST_TAG_ACS_RX",
// 70
       TAG_ATTRIBUTE"SLIST_TAG_ACS_TX",
// 71
       TAG_ATTRIBUTE"SLIST_TAG_UM",
// 72
       TAG_ATTRIBUTE"SLIST_TAG_UM_TSPI_TX",
// 73
       TAG_ATTRIBUTE"SLIST_TAG_SERVICE_TSPO_TX",
			"SERVICE_TSPO_TRANSMIT_PDU_Signal",
// 74
       TAG_ATTRIBUTE"SLIST_TAG_TSPI",
			"TSPI_START_TSPI_Signal",
// 75
		TAG_ATTRIBUTE"SLIST_TAG_TSPI_SERVICE_TX",
			"TSPI_SERVICE_RECEIVED_PDU_Signal",
			"TSPI_SERVICE_DISCONNECTION_Signal",
			"TSPI_SERVICE_CA_Signal",
// 76
		TAG_ATTRIBUTE"SLIST_TAG_TSPI_TSPO_TX",
			"TSPI_TSPO_NEW_CONNECTION_Signal",
			"TSPI_TSPO_SEND_CA_PDU_Signal",
			"TSPI_TSPO_DISCONNECTION_Signal",
			"TSPI_TSPO_GEtDEVDir_Signal",
// 77
		TAG_ATTRIBUTE"SLIST_TAG_TSPO_SERVICE_TX",
			"TSPO_SERVICE_SEND_ACK_Signal",
// 78
       TAG_ATTRIBUTE"SLIST_TAG_OAM",
// 79
       TAG_ATTRIBUTE"SLIST_TAG_OAM_TX",
// 80
       TAG_ATTRIBUTE"SLIST_TAG_OAM_RX",
// 81
       TAG_ATTRIBUTE"SLIST_TAG_DTRK_RX",
			"DTRK_TIMER_0_Signal",
			"DTRK_TIMER_1_Signal",
			"DTRK_TIMER_2_Signal",
			"DTRK_TIMER_3_Signal",
			"DTRK_TIMER_4_Signal",
			"DTRK_TIMER_5_Signal",
			"DTRK_DIGIT_SENT_Signal",
// 82
       TAG_ATTRIBUTE"SLIST_TAG_FRAMER_DTRK",
			"FRAMER_0_DETECT_Signal",
			"FRAMER_1_DETECT_Signal",
			"FRAMER_2_DETECT_Signal",
			"FRAMER_3_DETECT_Signal",
			"FRAMER_4_DETECT_Signal",
			"FRAMER_5_DETECT_Signal",
			"FRAMER_6_DETECT_Signal",
			"FRAMER_7_DETECT_Signal",
			"FRAMER_8_DETECT_Signal",
			"FRAMER_9_DETECT_Signal",
			"FRAMER_A_DETECT_Signal",
			"FRAMER_B_DETECT_Signal",
			"FRAMER_C_DETECT_Signal",
			"FRAMER_D_DETECT_Signal",
			"FRAMER_E_DETECT_Signal",
			"FRAMER_F_DETECT_Signal",
// 83
       TAG_ATTRIBUTE"SLIST_TAG_FRAMER_ALARM",
			"FRAMER_ALARM_STATUS_Signal",
// 84
       TAG_ATTRIBUTE"SLIST_TAG_ALARM_RX",
			"ALARM_STABLE_TIMER_Signal",
// 85
       TAG_ATTRIBUTE"SLIST_TAG_ALARM_DTRK",
			"ALARM_DTRK_ALARM_Signal",
// 86
       TAG_ATTRIBUTE"SLIST_TAG_ALARM_ADMIN",
			"ALARM_ADMIN_ALARM_Signal",
// 87
       TAG_ATTRIBUTE"SLIST_TAG_DEV_TX",
			"DEV_CM_ALERT_IND_Signal",
			"DEV_CM_ANSWER_IND_Signal",
			"DEV_CM_CALL_IND_Signal",
			"DEV_CM_CALL_PROCEEDING_Signal",
			"DEV_CM_CONNECT_REQ_CNF_Signal",
			"DEV_CM_DIGITS_RECEIVED_Signal",
			"DEV_CM_DISCONNECT_IND_Signal",
			"DEV_CM_RELEASE_COMPLETE_IND_Signal",
			"DEV_CM_RELEASE_IND_Signal",
			"DEV_CM_FLASH_IND_Signal",
			"DEV_CM_FLASH_CNF_Signal",
			"DEV_CM_PROGRESS_IND_Signal",
			"DEV_CM_DEFLECT_CALL_IND_Signal",
			"DEV_CM_ANSWER_CNF_Signal",
			"DEV_CM_CALL_PROCEEDING_CNF_Signal",
			"DEV_CM_START_DIGIT_COLLECT_CNF_Signal",
			"DEV_CM_DEVICE_IDLE_Signal",
			"DEV_CM_REQUEST_RESERVE_RSP_Signal",
			"DEV_CM_REPLACE_FSM_Signal",
// 88
       TAG_ATTRIBUTE"SLIST_TAG_TRMGR",
			"TRMGR_TIMER_TIMER_Signal",
// 89
       TAG_ATTRIBUTE"SLIST_TAG_DTP_TRMGR_TX",
			"TRMGR_DTP_DATA_IND_Signal",
			"TRMGR_DTP_SWITCH_DOWN_Signal",
			"TRMGR_DTP_SWITCH_UP_Signal",
// 90
       TAG_ATTRIBUTE"SLIST_TAG_CM_EPMGR_TX",
			"CM_RESERVE_ENDPOINT_Signal",
			"CM_CANCEL_ENDPOINT_RESERVATION_Signal",
// 91
       TAG_ATTRIBUTE"SLIST_TAG_CM_EPMGR_RX",
			"CM_RESERVE_ENDPOINT_RSP_Signal",
// 92
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_DRV_TX",
			"TRUNK_BLOCK_REQ_Signal",
			"TRUNK_UNBLOCK_REQ_Signal",
			"TRUNK_CALL_REQ_Signal",
			"TRUNK_INFO_REQ_Signal",
			"TRUNK_CALL_RSP_Signal",
			"TRUNK_CALL_PROC_REQ_Signal",
			"TRUNK_ALERT_REQ_Signal",
			"TRUNK_ANSWER_REQ_Signal",
			"TRUNK_DISCONNECT_REQ_Signal",
			"TRUNK_RELEASE_REQ_Signal",
			"TRUNK_RELEASE_RSP_Signal",
			"TRUNK_FLASH_REQ_Signal",
			"TRUNK_SEND_TONE_REQ_Signal",
			"TRUNK_START_DIGIT_COL_REQ_Signal",
			"TRUNK_STOP_DIGIT_COL_REQ_Signal",
			"TRUNK_TRANSIT_INFO_Signal",       // 15
			"TRUNK_NUMBER_COMPLETE_Signal",    // 16
			"TRUNK_SERVICE_REQ_Signal",        // 17
// 93
       TAG_ATTRIBUTE"SLIST_TAG_PG_RX",
// 94
       TAG_ATTRIBUTE"SLIST_TAG_RGMGR",
			"RGMGR_TIMER_TIMER_Signal",
			"RGMGR_PROCESS_Q_Signal",
// 95
       TAG_ATTRIBUTE"SLIST_TAG_DTP_RGMGR_TX",
			"RGMGR_DTP_DATA_IND_Signal",
			"RGMGR_DTP_SWITCH_DOWN_Signal",
			"RGMGR_DTP_SWITCH_UP_Signal",
// 96
       TAG_ATTRIBUTE"SLIST_TAG_DCM_CM_TX",
			"DCM_CM_CONNECT_CONFIRMED_Signal",
			"DCM_CM_REPLACE_CALLID_Signal",
			"DCM_CM_DEFLECT_CALL_IND_Signal",
			"DCM_CM_PICKUP_CNF_Signal",
			"DCM_CM_PICKUP_REJECT_Signal",
// 97
       TAG_ATTRIBUTE"SLIST_TAG_CM_VM_UTIL_RX",
			"VM_CM_MSG_CNT_Signal",
			"VVM_CM_VVMPACKET_Signal",
			"EXT_CM_VVMPACKET_Signal",
			"EXT_CM_VVM_LOGOFF_Signal",
// 98
       TAG_ATTRIBUTE"SLIST_TAG_CM_VM_UTIL_TX",
			"CM_EXT_MSG_CNT_Signal",
			"CM_VVM_VVMPACKET_Signal",
			"CM_EXT_VVMPACKET_Signal",
			"CM_VVM_LOGOFF_Signal",
// 99
       TAG_ATTRIBUTE"SLIST_TAG_HGMGR",
			"HGMGR_TIMER_TIMER_Signal",
			"HGMGR_PROCESS_Q_Signal",
// 100
       TAG_ATTRIBUTE"SLIST_TAG_DTP_HGMGR_TX",
			"HGMGR_DTP_DATA_IND_Signal",
			"HGMGR_DTP_SWITCH_DOWN_Signal",
			"HGMGR_DTP_SWITCH_UP_Signal",
// 101
       TAG_ATTRIBUTE"SLIST_TAG_GROUP_INTERNAL_TX",
			"HG_TIMER_TIMER_Signal",
			"HG_XC_CALLBACK_Signal",
// 102
       TAG_ATTRIBUTE"SLIST_TAG_RSERVER",
			"RSERVER_RECV_Signal",
			"RSERVER_SEND_Signal",
			"RSERVER_UP_Signal",
			"RSERVER_DOWN_Signal",
// 103
       TAG_ATTRIBUTE"SLIST_TAG_UM_TX",
			"UM_VM_PLAY_REQUEST_Signal",
			"UM_VM_STOP_REQUEST_Signal",
// 104
       TAG_ATTRIBUTE"SLIST_TAG_CTI_TSP_TX",
// 105
       TAG_ATTRIBUTE"SLIST_TAG_CTI_TSP_RX",
// 106
       TAG_ATTRIBUTE"SLIST_TAG_SMTP_RX",
			"SMTP_SEND_MAIL_Signal",
// 107
       TAG_ATTRIBUTE"SLIST_TAG_EXT_REQUEST_TX",
// 108
       TAG_ATTRIBUTE"SLIST_TAG_EXT_RESPONSE_TX",
			"EXT_CTI_SIGNAL_Signal",
// 109
       TAG_ATTRIBUTE"SLIST_TAG_CM_RECEIVE_REQUEST",
			"CM_RECEIVE_CONFERENCE_Signal",     
			"CM_RECEIVE_CONSULT_CALL_Signal",  
			"CM_RECEIVE_HOLD_CALL_Signal",      
			"CM_RETRIEVE_CALL_Signal",          
			"CM_TRANSFER_CALL_Signal",          
			"CM_LOOP_CALL_Signal",              
			"CM_RETRIEVE_LOOP_CALL_Signal",      
			"CM_ALTERNATE_CALL_Signal",
			"CM_RECONNECT_CALL_Signal",
			"CM_MUTE_SPEECH_PATH_Signal",
			"CM_CONFERENCE_SPLIT_Signal",     
			"CM_CONFERENCE_JOIN_Signal",     
			"CM_DIVERT_CALL_Signal",
			"CM_SNAPSHOT_DEVICE_Signal",
			"CM_ASSOCIATED_DATA_Signal",
			"CM_CALLBACK_REQUEST_Signal",
			"CM_CAB_FREE_NOT_RSP_Signal",
			"CM_CONF_RELEASE_DEVICE_Signal",
			"CM_CTI_CALL_BACK_Signal",
			"CM_CTI_CANCEL_CALL_BACK_Signal",
// 110
       TAG_ATTRIBUTE"SLIST_TAG_CM_TRANSMIT_RESPONSE",
			"CM_CTI_SIGNAL_Signal",
// 111
       TAG_ATTRIBUTE"SLIST_TAG_CM_XG_TX",
			"CM_XG_REPLACE_CALLED_CNF_Signal",
// 112
       TAG_ATTRIBUTE"SLIST_TAG_CDR",
			"CDR_NEW_ENTRY_Signal",
			"CDR_UPDATE_ENTRY_Signal",
			"CDR_START_SERVICE_Signal",
			"CDR_STOP_SERVICE_Signal",
			"CDR_AOC_INFO_Signal",
// 113
       TAG_ATTRIBUTE"SLIST_TAG_ISDN_INTERNAL",
			"ISDN_CALL_IN_Signal",
			"ISDN_SETUPACK_IN_Signal",
			"ISDN_DIGIT_IN_Signal",
			"ISDN_CALL_PROC_IN_Signal",  
			"ISDN_ALERT_IN_Signal",
			"ISDN_ANSWER_IN_Signal",
			"ISDN_DISCONNECT_IN_Signal",
			"ISDN_RELEASE_IN_Signal",
			"ISDN_PROGRESS_IN_Signal",
			"ISDN_ERR_IN_Signal",
			"ISDN_TRANSIT_INFO_Signal",
			"ISDN_FACILITY_CO_Signal",
			"ISDN_BLOCK_Signal",
			"ISDN_UNBLOCK_Signal",
// 114
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_TRUNK_TXRX",
			"TRUNK_TRANSIT_DATA_Signal",
// 115
       TAG_ATTRIBUTE"SLIST_TAG_MCID",
			"MCID_DISCONNECT_TIMER_Signal",
// 116
       TAG_ATTRIBUTE"SLIST_TAG_SERVICE",
			"MCID_REQ_Signal",
			"MCID_RSP_Signal",
// 117
       TAG_ATTRIBUTE"SLIST_TAG_MM_HDRV_TX",
			"MM_TX_HDRV_REGISTER_ACK_Signal",
			"MM_TX_HDRV_MEDIA_UPDATE_Signal",
// 118
       TAG_ATTRIBUTE"SLIST_TAG_MM",
// 119
       TAG_ATTRIBUTE"SLIST_TAG_DTP_MM_TX",
			"MM_DTP_DATA_IND_Signal",
			"MM_DTP_SWITCH_DOWN_Signal",
			"MM_DTP_SWITCH_UP_Signal",
// 120
       TAG_ATTRIBUTE"SLIST_TAG_IDRV",
			"IDRV_ENBLOC_TIMER_Signal",
// 121
       TAG_ATTRIBUTE"SLIST_TAG_TRMGR_TRUNK_TX",
			"TRMGR_TRUNK_GETINFO_REQ_Signal",
// 122
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_TRMGR_TX",
			"TRUNK_TRMGR_GETINFO_RSP_Signal",
// 123
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_TRDR_TX",
			"TRUNK_ATRKDR_CHECKVOLTAGE_REQ_Signal",
// 124
       TAG_ATTRIBUTE"SLIST_TAG_TRUNK_TRDR_RX",
			"TRUNK_ATRKDR_CHECKVOLTAGE_RSP_Signal",
// 125
       TAG_ATTRIBUTE"SLIST_TAG_WAPI",
			"WAPI_START_WAPI_Signal",
// 126
       TAG_ATTRIBUTE"SLIST_TAG_WAPI_SERVICE_TX",
			"WAPI_SERVICE_RECEIVED_PDU_Signal",
			"WAPI_SERVICE_DISCONNECTION_Signal",
			"WAPI_SERVICE_CA_Signal",
// 127
       TAG_ATTRIBUTE"SLIST_TAG_WAPI_WAPO_TX",
			"WAPI_WAPO_NEW_CONNECTION_Signal",
			"WAPI_WAPO_SEND_CA_PDU_Signal",
			"WAPI_WAPO_DISCONNECTION_Signal",
			"WAPI_WAPO_GETDEVDIR_Signal",
// 128
       TAG_ATTRIBUTE"SLIST_TAG_SERVICE_WAPO_TX",
			"SERVICE_WAPO_TRANSMIT_PDU_Signal",
// 129
       TAG_ATTRIBUTE"SLIST_TAG_EXTMGR",
			"EXTMGR_SUPERVISION_TIMER_Signal",
// 130
       TAG_ATTRIBUTE"SLIST_TAG_DTP_EXTMGR_TX",
			"EXTMGR_DTP_DATA_IND_Signal",
			"EXTMGR_DTP_SWITCH_DOWN_Signal",
			"EXTMGR_DTP_SWITCH_UP_Signal",

	   LIST_END
    };



char *StatesV300[] = {
	FSM_ATTRIBUTE"CM",
		"CM_STATE",
	FSM_ATTRIBUTE"DCM",
		"DCM_STATE",
    FSM_ATTRIBUTE"CFA",
		"CFA_IDLE",
		"CFA_RESERVED",
		"CFA_ANALYSING",
		"CFA_RELEASE",
    FSM_ATTRIBUTE"CFD",
		"CFD_IDLE",
		"CFD_RESERVED",
		"CFD_RELEASE",
	FSM_ATTRIBUTE"CTI",
		"CTI_STATE",
    FSM_ATTRIBUTE"DTRK",
		"DTRK_INACTIVE",
		"E1R2_IB_IDLE",
		"E1R2_OB_IDLE",
		"E1R2_TW_IDLE",
		"E1R2_IB_PEND_RSP",
		"E1R2_IB_DIGIT_COLLECT",
		"E1R2_IB_PEND_ANSWER",
		"E1R2_IB_PROC_ERR",
		"E1R2_IB_ANSWERED",
		"E1R2_IB_CLEAR_BACK",
		"E1R2_IB_SIM_ANSWER",
		"E1R2_OB_SEIZED",
		"E1R2_OB_SEIZED_ERR",
		"E1R2_OB_PREDIAL",
		"E1R2_OB_DIALING",
		"E1R2_OB_PEND_PROC",
		"E1R2_OB_CALL_PROC",
		"E1R2_OB_DIRECT_CONNECT",
		"E1R2_OB_PROC_ERR",
		"E1R2_OB_ANSWERED",
		"E1R2_OB_ANSWERED_ERR",
		"E1R2_OB_CLEAR_BACK",
		"E1R2_OB_CLEAR_FORWARD",
		"E1R2_DISC_BUSY_1",
		"E1R2_DISC_BUSY_2",
		"E1R2_PEND_RELEASE",
		"E1R2_PEND_CLEAR",
		"E1R2_PEND_IDLE",
		"E1R2_PEND_REL_RSP",
		"E1R2_DOUBLE_SEIZURE",
		"E1R2_INT_BLOCKED",
		"E1R2_REMOTE_BLOCKED",
		"E1R2_BLOCKED",
		"E1R2_ALARMED",
		"T1WNK_IB_IDLE",
		"T1WNK_OB_IDLE",
		"T1WNK_TW_IDLE",
		"T1WNK_IB_PEND_RSP",
		"T1WNK_IB_PREWINK",
		"T1WNK_IB_WINK",
		"T1WNK_IB_DIGIT_COLLECT",
		"T1WNK_IB_PEND_ANSWER",
		"T1WNK_IB_ANSWERED",
		"T1WNK_OB_SEIZED",
		"T1WNK_OB_WINK_BEGIN",
		"T1WNK_OB_PREDIAL",
		"T1WNK_OB_DIALING",
		"T1WNK_OB_PEND_PROC",
		"T1WNK_OB_CALL_PROC",
		"T1WNK_OB_DIRECT_CONNECT",
		"T1WNK_OB_ANSWERED",
		"T1WNK_OB_REMOTE_HANGUP",
		"T1WNK_DISC_BUSY_1",
		"T1WNK_DISC_BUSY_2",
		"T1WNK_PEND_RELEASE",
		"T1WNK_PEND_CLEAR",
		"T1WNK_PEND_IDLE",
		"T1WNK_PEND_REL_RSP",
		"T1WNK_BLOCKED",
		"T1WNK_ALARMED",
		"E1EL7_IDLE",
		"E1EL7_IB_RX_CDN",
		"E1EL7_IB_RINGING",
		"E1EL7_IB_PEND_ANSWER",
		"E1EL7_OB_SEIZED_PEND",
		"E1EL7_OB_PREDIAL",
		"E1EL7_OB_DIALING",
		"E1EL7_DIALING_FLASH",
		"E1EL7_OB_PEND_PROC",
		"E1EL7_OB_CALL_PROC",
		"E1EL7_OB_DIRECT_CONNECT",
		"E1EL7_CONNECTED",
		"E1EL7_CONNECT_FLASH",
		"E1EL7_PEND_RELEASE",
		"E1EL7_PEND_CLEAR",
		"E1EL7_PEND_IDLE",
		"E1EL7_PEND_REL_RSP",
		"E1EL7_LINE_ERROR",
		"E1EL7_BLOCKED",
		"E1EL7_ALARMED",
		"T1EL7_IDLE",
		"T1EL7_IB_RINGING",
		"T1EL7_IB_POST_RING",
		"T1EL7_OB_PEND_DIALTONE",
		"T1EL7_OB_PREDIAL",
		"T1EL7_OB_DIALING",
		"T1EL7_DIALING_FLASH",
		"T1EL7_OB_PEND_ANSWER",
		"T1EL7_OB_DIRECT_CONNECT",
		"T1EL7_CONNECTED",
		"T1EL7_CONNECT_FLASH",
		"T1EL7_PEND_RELEASE",
		"T1EL7_PEND_REL_RSP",
		"T1EL7_PEND_IDLE",
		"T1EL7_LINE_ERROR",
		"T1EL7_BLOCKED",
		"T1EL7_ALARMED",
    FSM_ATTRIBUTE"EXT",
		"EXT_IDLE",
		"EXT_ALERT_PENDING",
		"EXT_ALERTING",
		"EXT_OFFHOOK",
		"EXT_DIGITCOLLECT",
		"EXT_ANSWER_PENDING",
		"EXT_CONNECTED",
		"EXT_CONNECT_PENDING",
		"EXT_CALL_PROCEEDING",
		"EXT_DISCONNECT_INDICATION",
		"EXT_OFFHOOK_PENDING",
		"EXT_DISCONNECT_REQUEST",
		"EXT_OUT_OF_SERVICE",
		"EXT_RECALL_PENDING",
		"EXT_MAKE_CALL_PENDING",
		"EXT_ANSWER_CNF_PENDING",
		"EXT_CALL_PROCEEDING_CNF",
		"EXT_FLOATING",
		"EXT_RELEASE_PENDING",
		"EXT_TSP_ONHOOK",
		"EXT_IB_PENDING",
		"EXT_TSP_CANCEL_CONSULT_PENDING",
		"EXT_CAB_ALERT_PENDING",
		"EXT_CAB_REQUESTED",
		"EXT_RESERVED",
	FSM_ATTRIBUTE"EXTDR",
		"EXTDR_IDLE",
		"EXTDR_RINGING",
		"EXTDR_A_RING_STOPPING",
		"EXTDR_B_RING_STOPPING",
		"EXTDR_RING_IDLE_PEND",
		"EXTDR_RING_CONNECT_PEND",
		"EXTDR_CONNECT",
		"EXTDR_CP_TONE",
		"EXTDR_DIGIT_COLLECT",
		"EXTDR_DISC_BUSY",
		"EXTDR_DISCONNECT",
		"EXTDR_CID",
		"EXTDR_VWMI",
		"EXTDR_INACTIVE",
	FSM_ATTRIBUTE"HDRV",
		"HEXT_IDLE",
		"HEXT_OB_PENDING",
		"HEXT_OB_RINGING",
		"HEXT_IB_PENDING",
		"HEXT_CONNECT",
		"HEXT_DIGIT_COLLECT",
		"HEXT_CP_TONE",
		"HEXT_DISC_BUSY",
		"HEXT_DISCONNECT",
		"HTRK_IDLE",
		"HTRK_IB_PENDING",
		"HTRK_IB_RINGING",
		"HTRK_IB_ALERTING",
		"HTRK_IB_PEND_CONNECT",
		"HTRK_IB_PEND_ANSWER",
		"HTRK_OB_RX_TELNO",
		"HTRK_OB_RX_IPSTR",
		"HTRK_OB_PENDING",
		"HTRK_OB_ALERTING_LOCAL",
		"HTRK_OB_ALERTING_REMOTE",
		"HTRK_CONNECT",
		"HTRK_CONNECT_TONE",
		"HTRK_DIGIT_COLLECT",
		"HTRK_PEND_CLEAR",
		"HTRK_PEND_RELEASE",
		"HTRK_PEND_REL_RSP",
		"HTRK_BLOCKED",
		"HDRV_INACTIVE",
    FSM_ATTRIBUTE"IDRV",
		"IDRV_IDLE",
		"IDRV_CALL_INITIATED",
		"IDRV_ENBLOCSENDING",
		"IDRV_CALL_SETUP",
		"IDRV_CONNECT_PENDING",
		"IDRV_CALL_ACTIVE",
		"IDRV_DISCONNECT_REQUEST",
		"ISDN_RELEASE_PENDING",
		"ISDN_RELEASE_INDICATION",
		"ISDN_RELEASE_REQUEST",
		"ISDN_TRANSIT_PENDING",
		"IDRV_INACTIVE",
		"IDRV_BLOCKED",
    FSM_ATTRIBUTE"TRDR",
		"TRDR_IDLE",
		"TRDR_RING1_E",
		"TRDR_RING_OFF_E",
		"TRDR_JP_CAR_PEND",
		"TRDR_JP_CAR_OFF_PEND",
		"TRDR_JP_CID_PEND",
		"TRDR_RING1",
		"TRDR_CID_PEND",
		"TRDR_RING_OFF",
		"TRDR_RING2",
		"TRDR_POST_RING",
		"TRDR_IB_PEND_RSP_RING",
		"TRDR_IB_PEND_RSP_NORING",
		"TRDR_IB_DIGIT_COLLECT",
		"TRDR_IB_PEND_ANSWER",
		"TRDR_IB_CONNECT",
		"TRDR_IB_CONNECT_TONE",
		"TRDR_IB_CONNECT_DIGIT",
		"TRDR_OB_CONNECT_PEND",
		"TRDR_OB_DIALING",
		"TRDR_DIALING_FLASH",
		"TRDR_OB_ANSWER_PEND",
		"TRDR_OB_DIRECT_CONNECT",
		"TRDR_OB_CONNECT",
		"TRDR_OB_CONNECT_TONE",
		"TRDR_OB_CONNECT_DIGIT",
		"TRDR_CONNECT_FLASH",
		"TRDR_DISC_BUSY",
		"TRDR_PEND_RELEASE_1",
		"TRDR_PEND_RELEASE_2",
		"TRDR_HANGUP_PEND",
		"TRDR_REL_RSP_PEND",
		"TRDR_BLOCKED",
		"TRDR_INACTIVE",
    FSM_ATTRIBUTE"TRUNK",
		"TRUNK_CALL_IDLE",
		"TRUNK_OB_PENDING",
		"TRUNK_OB_PENDING_1",
		"TRUNK_IB_PENDING",
		"TRUNK_IB_PENDING_1",
		"TRUNK_OVERLAP_SENDING",
		"TRUNK_OVERLAP_RECEIVING",
		"TRUNK_OB_PROGRESS",
		"TRUNK_OB_CALL_PROC",
		"TRUNK_IB_CALL_PROC",
		"TRUNK_CALL_DELIVERED",
		"TRUNK_CALL_RECEIVED",
		"TRUNK_CALL_ACTIVE",
		"TRUNK_DISCONNECT_REQUEST",
		"TRUNK_DISCONNECT_INDICATED",
		"TRUNK_RELEASE_REQUEST",
		"TRUNK_RELEASE_INDICATED",
		"TRUNK_RELEASE_COMPLETE",
		"TRUNK_CALL_COLLISION",
		"TRUNK_BLOCKED",
		"TRUNK_INACTIVE",
	FSM_ATTRIBUTE"VPDRV",
		"VPDRV_CH_STATE_CLOSED",
		"VPDRV_CH_STATE_ALLOCATED",
		"VPDRV_CH_STATE_IDLE",
		"VPDRV_CH_STATE_VOICE",
		"VPDRV_CH_STATE_SND_LOOP",
		"VPDRV_CH_STATE_RCV_LOOP",
		"VPDRV_CH_STATE_FAX",
	FSM_ATTRIBUTE"CDR",
		"CDR_ACTIVE",
		"CDR_INACTIVE",
	FSM_ATTRIBUTE"AAM",
		"AAM_STATE",
	FSM_ATTRIBUTE"ACSM",
		"ACSM_STATE",
	FSM_ATTRIBUTE"CFM",
		"CFM_STATE",
	FSM_ATTRIBUTE"EXTM",
		"EXTM_STATE",
	FSM_ATTRIBUTE"HGMGR",
		"HGMGR_IDLE",
		"HGMGR_INACTIVE",
	FSM_ATTRIBUTE"MCID",
		"MCID_ACTIVE",
		"MCID_INACTIVE",
	FSM_ATTRIBUTE"RGMGR",
		"RGMGR_IDLE",
		"RGMGR_INACTIVE",
	FSM_ATTRIBUTE"TRMGR",
		"TRMGR_STATE",
	FSM_ATTRIBUTE"ISDN",
		"ISDN_INACTIVE",
		"ISDN_ACTIVE",
	FSM_ATTRIBUTE"MM",
		"MM_STATE_IDLE",
		"MM_STATE_ACTIVE",
	FSM_ATTRIBUTE"HG",
		"HG_STATE_IDLE",
		"HG_STATE_INACTIVE",
	FSM_ATTRIBUTE"PG",
		"PG_IDLE",
		"PG_CALLACTIVE",
		"PG_CONNECTPENDING",
		"PG_DISCONNECTPENDING",
	FSM_ATTRIBUTE"RG",
		"RG_STATE_IDLE",
		"RG_STATE_PENDING",
		"RG_STATE_LOCAL_BUSY",
		"RG_STATE_REMOTE_BUSY",
		"RG_STATE_INACTIVE",
	FSM_ATTRIBUTE"ALARM",
		"ALARM_IDLE",
		"ALARM_ACTIVE",
		"ALARM_PENDING",
	FSM_ATTRIBUTE"SMTP",
		"SMTP_IDLE",
	FSM_ATTRIBUTE"CLOG",
		"CLOG_IDLE",
		"CLOG_ACTIVE",
		"CLOG_INACTIVE",
	FSM_ATTRIBUTE"CMON",
		"CMON_IDLE",
	FSM_ATTRIBUTE"TSPI",
		"TSPI_IDLE",
	FSM_ATTRIBUTE"TSPO",
		"TSPO_IDLE",
	FSM_ATTRIBUTE"VM",
		"VM_IDLE",
		"VM_PLAY_AA",   
		"VM_PLAY_GREETING",
		"VM_RECORD_MESSAGE",
		"VM_USER_VERIFY",
		"VM_MAINMENU",
		"VM_REVIEW_MESSAGE",
		"VM_CONFIGMENU",
		"VM_PASSWORD_CHANGE",
		"VM_COLLECTDEST",
		"VM_GREETMENU",
		"VM_GET_MBOX_NUM",
		"VM_ADMIN_AA_MENU",
		"VM_EXIT",
		"VM_INUSE_EXIT",
		"VM_RECORD_PENDING",
		"VM_CM_RETURN_PEND",
		"VM_AA_TRANSF",
		"VM_VVM_PLAY",
		"VM_VVM_ALERT",
		"VM_POST_RECORD_MSG",
		"VM_POST_ABORT_REC_MSG",
		"VM_GREETREVIEW",
		"VM_GREETRECORD",
		"VM_GREETACTIVATE",
		"VM_DBN_GETNAME",
		"VM_DBN_PLAYNAMES",
		"VM_PASSWORD_CONFIRM",
		"VM_RECORDING_GREET",
		"VM_REVIEWING_GREET",
		"VM_END_REC_GREET",
		"VM_ABORT_REC_GREET",
		"VM_VM_RESOURCE_PEND",
		"VM_AA_RESOURCE_PEND",
		"VM_OUT_OF_SERVICE",
		"VM_AA_SCHEDULE",
		"VM_INIT",
		"VM_RECORDING_AA",
		"VM_END_REC_AA",
		"VM_ABORT_REC_AA",
		"VM_VVM_RESOURCE_PEND",
		"VM_DISCONNECT_IND",
		"VM_DISCONNECT_REQ",
		"VM_TRANSFER",
		"VM_RESTART_RESOURCE_PEND",
		"VM_EXT_NOTFOUND_PEND",
		"VM_REC_RESTART_PEND",
		"VM_UM_PLAY",
		"VM_UM_ALERT",
		"VM_UM_RESOURCE_PEND",
		"VM_AA_GREETRECORD",
		"VM_AA_GREETREVIEW",
		"VM_AA_TOGGLE_GREETING",
	FSM_ATTRIBUTE"VPDRV",
		"VPDRV_IDLE",
		"VPDRV_BUSY",
	FSM_ATTRIBUTE"VSCTL",
		"VSCTL_IDLE",
		"VSCTL_STREAM",
		"VSCTL_REC_FLUSH",
	FSM_ATTRIBUTE"WAPI",
		"WAPI_IDLE",
	FSM_ATTRIBUTE"WAPO",
		"WAPO_IDLE",
	FSM_ATTRIBUTE"TSPI",
		"TSPI_IDLE",
	FSM_ATTRIBUTE"DTP",
		"DTP_IDLE",
	FSM_ATTRIBUTE"DTPUT",
		"DTPUT_IDLE",
	FSM_ATTRIBUTE"WSHB",
		"WSHB_IDLE",
	FSM_ATTRIBUTE"CFG",
		"CFG_IDLE",
	FSM_ATTRIBUTE"OAM",
		"OAM_IDLE",
	FSM_ATTRIBUTE"SESM",
		"SESM_IDLE",
	FSM_ATTRIBUTE"SESU",
		"SESU_IDLE",
	FSM_ATTRIBUTE"TSPM",
		"TSPM_IDLE",
	FSM_ATTRIBUTE"TSPU",
		"TSPU_IDLE",
	FSM_ATTRIBUTE"XC",
		"XC_IDLE",
	FSM_ATTRIBUTE"H323",
		"H323_INACTIVE",
		"H323_ACTIVE",
	FSM_ATTRIBUTE"SIP",
		"SIP_INACTIVE",
		"SIP_ACTIVE",
	FSM_ATTRIBUTE"YP",
		"YP_STATE",
	FSM_ATTRIBUTE"MCIDM",
		"MCID_STATE",
	FSM_ATTRIBUTE"VVM",
		"VVM_STATE",
		"VVM_RES_PEND",
	FSM_ATTRIBUTE"ACS",
		"ACS_IDLE",
		"ACS_IDLE_PENDING",
		"ACS_CONNECT_PENDING",
		"ACS_CONNECTED_PLAYING_PHRASE",
		"ACS_CONNECTED_PLAYING_MUSIC",
		"ACS_DISCONNECT_INDICATED",
		"ACS_DISCONNECT_REQUESTED",
		"ACS_INACTIVE",

	LIST_END
};



char *EventsV300[] = {
    FSM_ATTRIBUTE"ACS",
		"ACS_TIMER_COMMON_TIMER_Event",           
		"ACS_TIMER_POSITION_TIMER_Event",
		"ACS_TIMER_COMFORT_MSG_TIMER_Event",
		"ACS_TIMER_FILE_TIMER_Event",
		"ACS_CM_ALERTING_RSP_Event",
		"ACS_CM_CALL_ANSWERED_Event", 
		"ACS_CM_CALL_PROCEEDING_Event",
		"ACS_CM_CONNECT_REQ_Event",
		"ACS_CM_CONNECT_CONFIRMED_Event",
		"ACS_CM_DISCONNECT_REQ_Event",
		"ACS_CM_FLASH_REQ_Event",
		"ACS_CM_RELEASE_REQ_Event",
		"ACS_CM_RELEASE_COMPLETE_REQ_Event",
		"ACS_CM_SEND_DIGITS_Event",
		"ACS_CM_START_DIGIT_COLLECT_Event",
		"ACS_CM_STOP_DIGIT_COLLECT_Event",	
		"ACS_CM_PROGRESS_REQ_Event",
		"ACS_CM_FLASH_RSP_Event",
		"ACS_CM_REPLACE_CALLID_Event",
		"ACS_CM_REQUEST_RESERVE_Event",
		"ACS_CM_REPLACE_FSM_Event",
		"ACS_PHR_DONE_STREAMING_Event",    
		"ACS_PHR_DONE_STREAMING_MSG_Event",
		"ACS_PHR_START_SESSION_Signal",
		"ACS_PHR_CLOSE_SESSION_Signal",
	FSM_ATTRIBUTE"CDR",
		"CDR_NEW_ENTRY_Event",				/* SLIST_TAG_CDR */
		"CDR_UPDATE_ENTRY_Event",
		"CDR_START_SERVICE_Event",
		"CDR_STOP_SERVICE_Event",
		"CDR_AOC_INFO_Event",
		"CDR_TSPI_RECEIVED_PDU_Event",		/* SLIST_TAG_TSPI_SERVICE_TX */
		"CDR_TSPI_DISCONNECT_Event",
		"CDR_TSPI_CA_Event",
	FSM_ATTRIBUTE"CTI",
	   "TSP_CTI_SIGNAL_Event",
	   "TSP_CTI_Disconnect_Event",
	   "EXT_CTI_SIGNAL_Event",
	   "CM_CTI_SIGNAL_Event",
	FSM_ATTRIBUTE"AAM",
	   "AAM_CM_RESERVE_ENDPOINT_Event",
	   "AAM_CM_CANCEL_RESERVE_ENDPOINT_EVENT",
	FSM_ATTRIBUTE"ACSM",
	   "ACSM_CM_RESERVE_ENDPOINT_Event",
	   "ACSM_CM_CANCEL_ENDPOINT_RESERVATION_Event",
	FSM_ATTRIBUTE"CFM",
	   "CFM_CM_RESERVE_ENDPOINT_Event",
	   "CFM_CM_CANCEL_ENDPOINT_RESERVATION_Event",
	FSM_ATTRIBUTE"EXTM",
		"EXTMGR_SUPERVISION_TIMER_Event",
		"EXTM_CM_RESERVE_ENDPOINT_Event",
		"EXTMGR_CM_CANCEL_ENDPOINT_RESERVATION_Event",
		"EXTMGR_DTP_DATA_IND_Event",
		"EXTMGR_DTP_SWITCH_DOWN_Event",
		"EXTMGR_DTP_SWITCH_UP_Event",
	FSM_ATTRIBUTE"HGMGR",
		"HGMGR_TIMER_TIMER_Event",                  //0  0 SLIST_TAG_HGMGR
		"HGMGR_PROCESS_Q_Event",                    //1  1 
		"HGMGR_CM_RESERVE_ENDPOINT_Event",          //2  0 SLIST_TAG_CM_EPMGR_TX
		"HGMGR_CM_CANCEL_RESERVE_ENDPOINT_Event",   //3  1
		"HGMGR_DTP_DATA_IND_Event",                 //4  0 SLIST_TAG_DTP_HGMGR_TX
		"HGMGR_DTP_SWITCH_DOWN_Event",              //5  1
		"HGMGR_DTP_SWITCH_UP_Event",                //6  2
		"HGMGR_YP_SWITCH_UP_Event",                 //7  0 SLIST_TAG_YP_TX
	FSM_ATTRIBUTE"MCIDM",
		"MCIDM_CM_RESERVE_ENDPOINT_Event",
		"MCIDM_CM_CANCEL_ENDPOINT_RESERVATION_Event",
	FSM_ATTRIBUTE"RGMGR",
		"RGMGR_TIMER_TIMER_Event",                  //0  0 SLIST_TAG_RGMGR
		"RGMGR_PROCESS_Q_Event",                    //1  1 
		"RGMGR_CM_RESERVE_ENDPOINT_Event",          //2  0 SLIST_TAG_CM_EPMGR_TX
		"RGMGR_CM_CANCEL_RESERVE_ENDPOINT_Event",   //3  1
		"RGMGR_DTP_DATA_IND_Event",                 //4  0 SLIST_TAG_DTP_RGMGR_TX
		"RGMGR_DTP_SWITCH_DOWN_Event",              //5  1
		"RGMGR_DTP_SWITCH_UP_Event",                //6  2
		"RGMGR_YP_SWITCH_UP_Event",                 //7  0 SLIST_TAG_YP_TX
	FSM_ATTRIBUTE"TRMGR",
		"TRMGR_TIMER_TIMER_Event",                    //0   SLIST_TAG_TRMGR
		"TRMGR_CM_RESERVE_ENDPOINT_Event",            //1   SLIST_TAG_CM_EPMGR_TX
		"TRMGR_CM_CANCEL_ENDPOINT_RESERVATION_Event", //2
		"TRMGR_DTP_DATA_IND_Event",                   //3   SLIST_TAG_DTP_TRMGR_TX
		"TRMGR_DTP_SWITCH_DOWN_Event",                //4
		"TRMGR_DTP_SWITCH_UP_Event",                  //5
		"TRMGR_TRUNK_GETINFO_RSP_Event",              //6
	FSM_ATTRIBUTE"MM",
		"MM_RX_HDRV_REGISTER_Event",                // 00
		"MM_RX_HDRV_UNREGISTER_Event",              // 01
		"MM_RX_HDRV_MEDIA_UPDATE_Event",            // 02 also for user input
		"MM_RX_HDRV_GEN_TONE_Event",                // 03 
		"MM_RX_VPM_DTMF_SENT_Event",                // 04
		"MM_RX_VPM_DTMF_DETECTED_Event",            // 05
		"MM_RX_VPM_FAX_DETECTED_Event",             // 06
		"MM_RX_XC_CREATE_Event",                    // 07
		"MM_RX_XC_SWITCH_Event",                    // 08
		"MM_RX_XC_DELETE_Event",                    // 09
		"MM_RX_XC_PREALLOCATE_Event",               // 0a
		"MM_RX_XC_ALLOCATE_Event",                  // 0b
		"MM_RX_XC_DEALLOCATE_Event",                // 0c
		"MM_RX_XC_ECON_Event",                      // 0d
		"MM_RX_XC_ECOFF_Event",                     // 0e
		"MM_RX_TIMER_Event",			             // 0f
		"MM_RX_DTP_DATA_IND_Event",                 // 0g SLIST_TAG_DTP_MM_TX
		"MM_RX_DTP_SWITCH_DOWN_Event",              // 11
		"MM_RX_DTP_SWITCH_UP_Event",                // 12
	FSM_ATTRIBUTE"CM",
		"CM_TIMER_TIMER_Event",				//0 cm to cm stuff	SLIST_TAG_CM
		"CM_XC_CALLBACK_Event",            	//1
		"CM_XFER_RQ_Event",                	//2
		"CM_ACQUIRE_CALL_Event",           	//3
		"CM_PARK_DISCONNECT_Event",        	//4
		"CM_PICKUP_IND_Event",             	//5
		"CM_PROVIDE_MUSIC_Event",				//6
		"CM_REMOVE_MUSIC_REQ_Event",       	//7
		"CM_REMOVE_MUSIC_RSP_Event",			//8
		"CM_ACQUIRE_CALL_CNF_Event",       	//9
		"CM_RECALL_Event",                 	//10
		"CM_DEFLECT_CALL_REQ_Event",       	//11
		"CM_PICKUP_CNF_Event",			    //12
		"CM_PICKUP_REJECT_Event",		    	//13
		"CM_CONFERENCE_REQ_Event",			//14
		"CM_CONFERENCE_RSP_Event",			//15
		"CM_CONNECT_REQ_CNF_Event",        	//16
		"CM_REROUTE_IND_Event",            	//17
		"CM_TAG_ASSOCIATED_DATA_Event",    	//18
		"CM_CAB_ACTIVATE_REQUEST_Event",   	//19
		"CM_CAB_FREE_NOTIFICATION_Event",  	//20
		"CM_CAB_CANCELATION_Event",        	//21
		"CM_CAB_ACTIVATE_RESPONSE_Event",  	//22
		"CM_CAB_SUSPEND_Event",				//23
		"CM_CAB_RESUME_Event",             	//24
		"CM_REPORT_TRANSFER_Event",        	//25 
		"CM_REROUTE_CALL_EVent",				//26
		"CM_INTERNAL_DATA_IND_Event",      	//27
		"CM_INTERNAL_DATA_RSP_Event",      	//28
		"CM_SEND_DIGITS_CNF_Event",        	//29
		"CM_REPLACE_CALLID_CONF_TO_NORMAL",	//30
		"CM_REPLACE_CALLID_CONF_TO_NORMAL_RSP", 	//31
		"CM_ALERT_IND_Event",					//32 device to cm stuff SLIST_TAG_DEV_TX
		"CM_ANSWER_IND_Event",             	//33
		"CM_CALL_IND_Event",               	//35
		"CM_CALL_PROCEEDING_Event",        	//36
		"CM_CONN_REQ_CNF_Event",           	//36
		"CM_DIGITS_RECEIVED_Event",        	//37
		"CM_DISCONNECT_IND_Event",         	//38
		"CM_REL_COMPLETE_IND_Event",       	//39
		"CM_RELEASE_IND_Event",            	//40
		"CM_FLASH_IND_Event",              	//41
		"CM_FLASH_CNF_Event",              	//42
		"CM_PROGRESS_IND_Event",           	//43 
		"CM_DEFLECT_CALL_IND_Event",       	//44
		"CM_ANSWER_CNF_Event",			    //45
		"CM_CALL_PROCEEDING_CNF_Event",    	//46
		"CM_START_DIGIT_COLLECT_CNF_Event",	//47
		"CM_DEVICE_IDLE_Event",            	//48
		"CM_REQUEST_RESERVE_RSP_Event",    	//49
		"CM_REPLACE_FSM_Event",				//50
		"CM_REPLACE_CALLED_Event",         	//51
		"CM_MCID_REQ_Event",               	//52
		"CM_MCID_RSP_Event",		        	//53
		"CM_RESERVE_ENDPOINT_RESP_Event",  	//54 SLIST_TAG_" Device Manager to CM
		"CM_VM_DIGITSTOP_IND_Event",       	//55 aa to cm stuff	SLIST_TAG_VM_CM
		"CM_VM_INSPEECHDIGITS_IND_Event",  	//56
		"CM_VM_REROUTE_IND_Event",         	//57
		"CM_VM_XFER_RESTART_CNF_Event",    	//58         
		"CM_DCM_CONNECT_CONFIRM_Event",    	//59  SLIST_TAG_DCM_CM_TX
		"CM_DCM_REPLACE_CALLID_Event",     	//60
		"CM_DCM_DEFLECT_CALL_IND_Event",   	//61
		"CM_DCM_PICKUP_CNF_Event",	        //62
		"CM_DCM_PICKUP_REJECT_Event",	    	//63
		"CM_VM_NEW_MSG_CNT_Event",         	//64  SLIST_TAG_CM_VM_UTIL_RX 
		"CM_VVM_VVMPACKET_Event",	        	//65
		"CM_EXT_VVMPACKET_Event",	        	//66
		"CM_VVM_LOGOFF",                   	//67
		"DSP_DTMF_DETECT_Event",          	 //68  SLIST_TAG_DSP
		"DSP_BANKSWITCH_Event",    	    	//69
		"DSP_TONE_DETECT_Event",           	//70
		"DSP_CID_DETECT_Event",	        	//71
		"CM_DTMF_SENT_Event",              	//72
		"CM_RECEIVE_CONFERENCE_Event",     	//73  SLIST_TAG_CM_RECEIVE_REQUEST
		"CM_RECEIVE_CONSULT_CALL_Event",   	//74
		"CM_RECEIVE_HOLD_CALL_Event",      	//75
		"CM_RETRIEVE_CALL_Event",          	//76
		"CM_TRANSFER_CALL_Event",          	//77
		"CM_LOOP_CALL_Event",              	//78
		"CM_RETRIEVE_LOOP_CALL_Event",     	//79
		"CM_ALTERNATE_CALL_Event",         	//80
		"CM_RECONNECT_CALL_Event",         	//81
		"CM_MUTE_SPEECH_PATH_Event",       	//82
		"CM_CONFERENCE_SPLIT_Event",       	//83
		"CM_CONFERENCE_JOIN_Event",        	//84
		"CM_DIVERT_CALL_Event",            	//85
		"CM_SNAPSHOT_Event",               	//86
		"CM_ASSOCIATED_DETA_Event",        	//87    
		"CM_CALLBACK_REQ_Event",           	//88
		"CM_CAB_FREE_NOT_RSP_Event",       	//89
		"CM_CONF_RELEASE_DEVICE_Event",    	//90
		"CM_CTI_CALL_BACK_Event",				//91
		"CM_CTI_CANCEL_CALL_BACK_Event",   	//92
	FSM_ATTRIBUTE"DCM",
		"DCM_TIMER_TIMER_Event",              //0   SLIST_TAG_"DCM
		"DCM_DTP_DATA_IND_Event",             //1   SLIST_TAG_DTP_"DCM_TX
		"DCM_DTP_SWITCH_DOWN_Event",          //2
		"DCM_DTP_SWITCH_UP_Event",            //3
		"DCM_CM_ALERTING_RSP_Event",          //4   SLIST_TAG_CM_TX
		"DCM_CM_CALL_ANSWERED_Event", 		   //5
		"DCM_CM_CALL_PROCEEDING_Event",       //6
		"DCM_CM_CONNECT_REQ_Event",		   //7
		"DCM_CM_CONNECT_CONFIRMED_Event",     //8
		"DCM_CM_DISCONNECT_REQ_Event",		   //9
		"DCM_CM_FLASH_REQ_Event",			   //10
		"DCM_CM_RELEASE_REQ_Event",		   //11
		"DCM_CM_RELEASE_COMPLETE_REQ_Event",  //12
		"DCM_CM_SEND_DIGITS_Event",		   //13
		"DCM_CM_START_DIGIT_COLLECT_Event",   //14
		"DCM_CM_STOP_DIGIT_COLLECT_Event",	   //15
		"DCM_CM_PROGRESS_REQ_Event",		   //16
		"DCM_CM_FLASH_RSP_Event",             //17
		"DCM_CM_REPLACE_CALLID_Event",        //18
		"DCM_CM_REQUEST_RESERVE_Event",       //19
		"DCM_CM_REPLACE_FSM_Event",		   //20
		"DCM_CM_NUMBER_COMPLETE_Event",       //21
		"DCM_YP_IP_DOWN_Event",               //22  SLIST_TAG_YP_TX
		"DCM_CM_TIMER_TIMER_Event",           //23  SLIST_TAG_CM   
		"DCM_CM_XC_CALLBACK_Event",           //24
		"DCM_CM_XFER_REQ_Event",              //25
		"DCM_CM_ACQUIRE_CALL_Event",          //26
		"DCM_CM_PARK_DISCONNECT_Event",       //27
		"DCM_CM_PICKUP_IND_Event",            //28
		"DCM_CM_PROVIDE_MUSIC_Event",		   //29	
		"DCM_CM_REMOVE_MUSIC_REQ_Event",      //30
		"DCM_CM_REMOVE_MUSIC_RSP_Event",	   //31
		"DCM_CM_ACQUIRE_CALL_CNF_Event",      //32
		"DCM_CM_RECALL_Event",                //33
		"DCM_CM_DEFLECT_CALL_REQ_Event",      //34
		"DCM_CM_PICKUP_CNF_Event",			   //35
		"DCM_CM_PICKUP_REJECT_Event",		   //36
		"DCM_CM_CONFERENCE_REQ_Event",		   //37
		"DCM_CM_CONFERENCE_RSP_Event",		   //38
		"DCM_CM_CONN_REQ_CNF_Event",          //39
		"DCM_CM_REROUTE_IND_Event",           //40
		"DCM_CM_TAG_ASSOCIATED_DATA_Event",   //41
		"DCM_CM_CAB_ACTIVATE_REQUEST_Event",  //42
		"DCM_CM_CAB_FREE_NOTIFICATION_Event", //43
		"DCM_CM_CAB_CANCELATION_Event",       //44
		"DCM_CM_CAB_ACTIVATE_RESPONSE_Event", //45
		"DCM_CM_CAB_SUSPEND_Event",           //46
		"DCM_CM_CAB_RESUME_Event",            //47
		"DCM_CM_REPORT_TRANSFER_Event",       //48
		"DCM_CM_REROUTE_CALL_Event",		   //49
		"DCM_CM_INTERNAL_DATA_IND_Event",     //50
		"DCM_CM_INTERNAL_DATA_RSP_Event",     //51
		"DCM_CM_SEND_DIGITS_CNF_Event",       //52
		"DCM_CM_CONF_TO_REGULAR_REPLACE_CALLID_Event",		//53 
		"DCM_CM_CONF_TO_REGULAR_REPLACE_CALLID_RSP_Event",  //54
		"DCM_TRANSIT_INFO_Event",             //55
		"DCM_MCID_REQ_Event",                 //56	 SLIST_TAG_SERVICE
		"DCM_MCID_RSP_Event",                 //57 
	FSM_ATTRIBUTE"EXT",
		"EXT_TIMER_TIMER_Event",                 // 0 SLIST_TAG_EXT
		"EXT_TIMER_START_DIGIT_TIMEOUT_Event",   // 1
		"EXT_TIMER_INTER_DIGIT_TIMEOUT_Event",   // 2
		"EXT_RECALL_TIMER_Event",                // 3
		"EXT_EXTDR_OFFHOOK_IND_Event",           // 4 SLIST_TAG_EXT_DRV_TX
		"EXT_EXTDR_ONHOOK_IND_Event",            // 5
		"EXT_EXTDR_FLASH_KEY_IND_Event",         // 6
		"EXT_EXTDR_ERR_IND_Event",               // 7
		"EXT_EXTDR_RING_IND_Event",              // 8
		"EXT_EXTDR_DIGIT_RECEIVED_IND_Event",    // 9
		"EXT_EXTDR_MAKE_CALL_IND_Event",         //10
		"EXT_EXTDR_ANSWER_CNF_Event",            //11
		"EXT_EXTDR_CALL_PROC_CNF_Event",         //12
		"EXT_EXTDR_DIGIT_COLL_CNF_Event",		  //13
		"EXT_EXTDR_ALERT_RSP_CNF_Event",         //14  
		"EXT_EXTDR_CTI_LOGON_Event",             //15
		"EXT_EXTDR_CTI_LOGOFF_Event",            //16
		"EXT_CM_ALERTING_RSP_Event",	          //17 SLIST_TAG_CM_TX
		"EXT_CM_CALL_ANSWERED_Event",            //
		"EXT_CM_CALL_PROCEEDING_Event",          //19
		"EXT_CM_CONNECT_REQ_Event",	          //		 	
		"EXT_CM_CONNECT_CONFIRMED_Event",        //
		"EXT_CM_DISCONNECT_REQ_Event",           //22
		"EXT_CM_FLASH_REQ_Event",                //
		"EXT_CM_RELEASE_REQ_Event",              //
		"EXT_CM_RELEASE_COMPLETE_REQ_Event",     //
		"EXT_CM_SEND_DIGITS_Event",              //
		"EXT_CM_START_DIGIT_COLLECT_Event",      //25
		"EXT_CM_STOP_DIGIT_COLLECT_Event",       //
		"EXT_CM_PROGRESS_REQ_Event",             //
		"EXT_CM_FLASH_RSP_Event",                //
		"EXT_CM_REPLACE_CALLID_Event",           //
		"EXT_CM_REQUEST_RESERVE_Event",          //30
		"EXT_CM_REPLACE_FSM_Event",              //
		"EXT_CM_NUMBER_COMPLETE_Event",          //
		"EXT_CM_CAB_FREE_NOTIFICATION_Event",    //
		"EXT_CM_CABREQUEST_RSP_Event",           //
		"EXT_CM_CABRESUME_Event",                //35
		"TSP_EXT_MAKE_CALL_Event",               //  SLIST_TAG_TSP_EXT_TX 
		"TSP_EXT_HANGUP_Event",                  //  
		"TSP_EXT_DETACH_Event",                  //
		"TSP_EXT_HOLD_Event",                    //  
		"TSP_EXT_CANCEL_HOLD_Event",             //40   
		"TSP_EXT_TRANSFER_Event",                //  
		"TSP_EXT_FORWARD_Event",                 //  
		"TSP_EXT_CANCEL_FORWARD_Event",          //  
		"TSP_EXT_PICKUP_Event",                  //  
		"TSP_EXT_CONFERENCE_Event",              //45  
		"TSP_EXT_CONSULT_Event",                 //  
		"EXT_TSP_CANCEL_CONSULT_Event",          //  
		"EXT_TSP_GET_STATUS_Event",              //
		"TSP_EXT_VVMPACKET_Event",               //
		"TSP_EXT_DTMF_Event",                    //50  
		"TSP_EXT_FLASH_Event",                   // 
		"TSP_EXT_ATTACH_REQUEST_Event",          //
		"VM_CM_MSG_CNT_Event",                   //  SLIST_TAG_CM_VM_UTIL_TX
		"EXT_VVM_VVM_PACKET_Event",              //
		"EXT_CM_VVM_PACKET_Event",				  //
		"EXT_CM_VVM_LOGOFF_Event",				  //55
	FSM_ATTRIBUTE"HG",
		"HG_TIMER_TIMER_Event",               //0   -  0
		"HG_XC_CALLBACK_Event",               //1      1
		"CM_HG_ALERTING_RSP_Event",           //2   -  0   SLIST_TAG_CM_TX
		"CM_HG_CALL_ANSWERED_Event",          //3   -  1
		"CM_HG_CALL_PROCEEDING_Event",        //4   -  2
		"CM_HG_CONNECT_REQ_Event",            //5   -  3
		"CM_HG_CONNECT_CONFIRMED_Event",      //6   -  4
		"CM_HG_DISCONNECT_REQ_Event",         //7   -  5
		"CM_HG_FLASH_REQ_Event",              //8   -  6
		"CM_HG_RELEASE_REQ_Event",            //9   -  7
		"CM_HG_RELEASE_COMPLETE_REQ_Event",   //10   -  8
		"CM_HG_SEND_DIGITS_Event",            //11  -  9
		"CM_HG_START_DIGIT_COLLECT_Event",    //12  -  10
		"CM_HG_STOP_DIGIT_COLLECT_Event",     //13  -  11
		"CM_HG_PROGRESS_REQ_Event",           //14  -  12
		"CM_HG_FLASH_RSP_Event",              //15  -  13
		"CM_HG_REPLACE_CALLID_Event",         //16  -  14
		"CM_HG_REQUEST_RESERVE_Event",        //17  -  15    
		"CM_HG_REPLACE_FSM_Event",            //18  -  16
		"CM_HG_NUMBER_COMPLETE_Event",        //19  -  18
		"HG_CM_ALERT_IND_Event",	       //20  -  0  Device to cm stuff SLIST_TAG_DEV_TX
		"HG_CM_ANSWER_IND_Event",             //21  -  1
		"HG_CM_CALL_IND_Event",               //22  -  2
		"HG_CM_CALL_PROCEEDING_Event",        //23  -  3
		"HG_CM_CONN_REQ_CNF_Event",           //24  -  4
		"HG_CM_DIGITS_RECEIVED_Event",        //25  -  5
		"HG_CM_DISCONNECT_IND_Event",         //26  -  6
		"HG_CM_REL_COMPLETE_IND_Event",       //27  -  7
		"HG_CM_RELEASE_IND_Event",            //28  -  8
		"HG_CM_FLASH_IND_Event",              //29  -  9
		"HG_CM_FLASH_RESP_Event",             //30  -  10
		"HG_CM_PROGRESS_IND_Event",           //31  -  11
		"HG_CM_DEFLECT_CALL_IND_Event",       //32  -  12
		"HG_CM_RESERVE_ENDPOINT_RSP_Event",   //33  -  0  Device Manager to CM
		"HG_DCM_CONNECT_CONFIRM_Event",       //34  SLIST_TAG_DCM_CM_TX
		"HG_DCM_REPLACE_CALLID_Event",        //35
		"HG_DCM_DEFLECT_CALL_IND_Event",      //36
		"HG_DCM_PICKUP_CNF_Event",	       //37
		"HG_DCM_PICKUP_REJECT_Event",	   	//38
		"CM_XG_REPLACE_CALLED_CNF_Event",     //39   SLIST_TAG_CM_XG_TX
	FSM_ATTRIBUTE"PG",
		"PG_TIMER_TIMER_Event",
		"PG_ALERTING_RSP_Event",
		"PG_CALL_ANSWERED_Event", 
		"PG_CALL_PROCEEDING_Event",
		"PG_CONNECT_REQ_Event",
		"PG_CONNECT_CONFIRMED_Event",
		"PG_DISCONNECT_REQ_Event",
		"PG_FLASH_REQ_Event",
		"PG_RELEASE_REQ_Event",
		"PG_RELEASE_COMPLETE_REQ_Event",
		"PG_SEND_DIGITS_Event",
		"PG_START_DIGIT_COLLECT_Event",
		"PG_STOP_DIGIT_COLLECT_Event",
		"PG_PROGRESS_REQ_Event",
		"PG_FLASH_RSP_Event",
		"PG_REPLACE_CALLID_Event",
		"PG_REQUEST_RESERVE_Event",
		"PG_CM_REPLACE_FSM_Event",
		"PG_CM_NUMBER_COMPLETEEvent",
	FSM_ATTRIBUTE"RG",
		"RG_TIMER_TIMER_Event",               //0   -  0
		"RG_XC_CALLBACK_Event",               //1      1
		"CM_RG_ALERTING_RSP_Event",           //2   -  0   SLIST_TAG_CM_TX
		"CM_RG_CALL_ANSWERED_Event",          //3   -  1
		"CM_RG_CALL_PROCEEDING_Event",        //4   -  2
		"CM_RG_CONNECT_REQ_Event",            //5   -  3
		"CM_RG_CONNECT_CONFIRMED_Event",      //6   -  4
		"CM_RG_DISCONNECT_REQ_Event",         //7   -  5
		"CM_RG_FLASH_REQ_Event",              //8   -  6
		"CM_RG_RELEASE_REQ_Event",            //9   -  7
		"CM_RG_RELEASE_COMPLETE_REQ_Event",   //10   -  8
		"CM_RG_SEND_DIGITS_Event",            //11  -  9
		"CM_RG_START_DIGIT_COLLECT_Event",    //12  -  10
		"CM_RG_STOP_DIGIT_COLLECT_Event",     //13  -  11
		"CM_RG_PROGRESS_REQ_Event",           //14  -  12
		"CM_RG_FLASH_RSP_Event",              //15  -  13
		"CM_RG_REPLACE_CALLID_Event",         //16  -  14
		"CM_RG_RESERVE_REQUEST_Event",        //17  -  15
		"CM_RG_REPLACE_FSM_Event",			   //18  -  16
		"CM_RG_NUMBER_COMPLETE_Event",        //19  -  17
		"RG_CM_ALERT_IND_Event",			   //20  -  0  Device to cm stuff SLIST_TAG_DEV_TX
		"RG_CM_ANSWER_IND_Event",             //21  -  1
		"RG_CM_CALL_IND_Event",               //22  -  2
		"RG_CM_CALL_PROCEEDING_Event",        //23  -  3
		"RG_CM_CONN_REQ_CNF_Event",           //24  -  4
		"RG_CM_DIGITS_RECEIVED_Event",        //25  -  5
		"RG_CM_DISCONNECT_IND_Event",         //26  -  6
		"RG_CM_REL_COMPLETE_IND_Event",       //27  -  7
		"RG_CM_RELEASE_IND_Event",            //28  -  8
		"RG_CM_FLASH_IND_Event",              //29  -  9
		"RG_CM_FLASH_RESP_Event",             //30  -  10
		"RG_CM_PROGRESS_IND_Event",           //31  -  11
		"RG_CM_DEFLECT_CALL_IND_Event",       //32  -  12
		"RG_CM_RESERVE_ENDPOINT_RSP_Event",   //33  -  0  Device Manager to CM
		"CM_RG_REPLACE_CALLED_CNF_Event",     //34  -  0   SLIST_TAG_CM_XG_TX
	FSM_ATTRIBUTE"TRUNK",
		"TRUNK_CM_ALERTING_RSP_Event",           //  0
		"TRUNK_CM_CALL_ANSWERED_Event",          //  1
		"TRUNK_CM_CALL_PROCEEDING_Event",        //  2
		"TRUNK_CM_CONNECT_REQ_Event",            //  3 
		"TRUNK_CM_CONNECT_CONFIRMED_Event",      //  4
		"TRUNK_CM_DISCONNECT_REQ_Event",         //  5
		"TRUNK_CM_FLASH_REQ_Event",              //  6
		"TRUNK_CM_RELEASE_REQ_Event",            //  7
		"TRUNK_CM_RELEASE_COMPLETE_REQ_Event",   //  8
		"TRUNK_CM_SEND_DIGITS_Event",            //  9 
		"TRUNK_CM_START_DIGIT_COLLECT_Event",    // 10
		"TRUNK_CM_STOP_DIGIT_COLLECT_Event",     // 11
		"TRUNK_CM_PROGRESS_REQ_Event",           // 12
		"TRUNK_CM_FLASH_RSP_Event",              // 13
		"TRUNK_CM_REPLACE_CALLID_Event",         // 14
		"TRUNK_CM_REQUEST_RESERVE_Event",        // 15     
		"TRUNK_CM_REPLACE_FSM_Event",            // 16
		"TRUNK_CM_NUMBER_COMPLETE_Event",        // 17
		"TRUNK_TRDR_ERROR_IND_Event",            // 18
		"TRUNK_TRDR_ERROR_CLEARED_IND_Event",    // 19
		"TRUNK_TRDR_CALL_IND_Event",             // 20
		"TRUNK_TRDR_INFO_IND_Event",             // 21
		"TRUNK_TRDR_CALL_CNF_Event",             // 22
		"TRUNK_TRDR_CALL_PROC_IND_Event",        // 23
		"TRUNK_TRDR_ALERT_IND_Event",            // 24
		"TRUNK_TRDR_ANSWER_IND_Event",           // 25
		"TRUNK_TRDR_DISCONNECT_IND_Event",       // 26
		"TRUNK_TRDR_RELEASE_IND_Event",          // 27
		"TRUNK_TRDR_RELEASE_CNF_Event",          // 28
		"TRUNK_TRDR_FLASH_CNF_Event",            // 29
		"TRUNK_TRDR_PROGRESS_IND_Event",         // 30
		"TRUNK_TRDR_ANSWER_CNF_Event",           // 31
		"TRUNK_TRDR_START_DIGIT_COL_CNF_Event",  // 32 
		"TRUNK_TRDR_STOP_DIGIT_COL_CNF_Event",   // 33
		"TRUNK_TRDR_TRANSIT_INFO_Event",         // 34
		"TRUNK_TRDR_SERVICE_RSP_Event",          // 35
		"TRUNK_TRDR_CALL_PROC_CNF_Event",        // 36
		"TRUNK_TRUNK_TRANSIT_DATA_Event",        // 37
		"TRUNK_MCID_REQ_Event",                  // 38
		"TRUNK_TRMGR_GETINFO_REQ_Event",         // 39
		"TRUNK_ATRKDR_CHECKVOLTAGE_RSP_Event",   // 40
	FSM_ATTRIBUTE"ALARM",
	   "ALARM_STABLE_TIMER_Event",              // (SLIST_TAG_ALARM_RX)
	   "ALARM_FRAMER_ALARM_Event",       // (SLIST_TAG_FRAMER_ALARM)
	FSM_ATTRIBUTE"TRDR",
		"TRDR_DIALTONE_TIMER_Event",             // 0
		"TRDR_HANGUP_TIMER_Event",               // 1
		"TRDR_ONHOOK_TIMER_Event",               // 2
		"TRDR_OFFHOOK_TIMER_Event",              // 3
		"TRDR_RING_FILTER_TIMER_Event",          // 4
		"TRDR_SECOND_RING_TIMER_Event",          // 5
		"TRDR_RINGON_GUARD_TIMER_Event",         // 6
		"TRDR_POLARITY_FILTER_TIMER_Event",      // 7
		"TRDR_POL_PEND_TIMER_Event",             // 8
		"TRDR_CHECK_VOLTAGE_TIMER_Event",        // 9
		"TRDR_FLASH_TIMER_Event",                // 10
		"TRDR_DIGIT_SENT_Event",                 // 11
		/* Ring-detect interface */
		"TRDR_RING_ON_DETECT_Event",             // 12
		"TRDR_RING_OFF_DETECT_Event",            // 13
		/* Trunk request events */
		"TRUNK_BLOCK_REQ_Event",                 // 14
		"TRUNK_UNBLOCK_REQ_Event",               // 15
		"TRUNK_CALL_REQ_Event",                  // 16
		"TRUNK_INFO_REQ_Event",                  // 17
		"TRUNK_CALL_RSP_Event",                  // 18
		"TRUNK_CALL_PROC_REQ_Event",             // 19
		"TRUNK_ALERT_REQ_Event",                 // 20
		"TRUNK_ANSWER_REQ_Event",                // 21
		"TRUNK_DISCONNECT_REQ_Event",            // 22
		"TRUNK_RELEASE_REQ_Event",               // 23
		"TRUNK_RELEASE_RSP_Event",               // 24
		"TRUNK_FLASH_REQ_Event",                 // 25
		"TRUNK_SEND_TONE_REQ_Event",             // 26
		"TRUNK_START_DIGIT_COL_REQ_Event",       // 27
		"TRUNK_STOP_DIGIT_COL_REQ_Event",        // 28
		"TRUNK_TRANSIT_INFO_Event",		      // 29
		"TRUNK_NUMBER_COMPLETE_Event",	          // 30
		/* QSLAC driver events */                  
		"TRDR_QSLAC_OFFHOOK_Event",              // 31
		"TRDR_QSLAC_ONHOOK_Event",               // 32
		"TRDR_QSLAC_LINE_REVERSAL_Event",        // 33
		/* DSP driver events */
		"TRDR_DSP_DTMF_DETECT_Event",            // 34
		"TRDR_DSP_BANKSWITCH_Event",             // 35
		"TRDR_DSP_TONE_DETECT_Event",            // 36
		"TRDR_DSP_CID_DETECT_Event",             // 37
		"TRDR_DSP_TONE_SENT_Event",              // 38
		/* Trunk to ATRKDRV events */
		"TRUNK_CHECK_VOLTAGE_Event",             // 39
	FSM_ATTRIBUTE"DTRK",
		"DTRK_TIMER_0_Event",                    // 0 (SLIST_TAG_"DTRK_RX)
		"DTRK_TIMER_1_Event",                    // 1 
		"DTRK_TIMER_2_Event",                    // 2 
		"DTRK_TIMER_3_Event",                    // 3
		"DTRK_TIMER_4_Event",                    // 4 
		"DTRK_TIMER_5_Event",                    // 5 
		"DTRK_DIGIT_SENT_Event",                 // 6
		/* Trunk request events */
		"DTRK_TRUNK_BLOCK_REQ_Event",            // 7
		"DTRK_TRUNK_UNBLOCK_REQ_Event",          // 8
		"DTRK_TRUNK_CALL_REQ_Event",             // 9
		"DTRK_TRUNK_INFO_REQ_Event",             // 10
		"DTRK_TRUNK_CALL_RSP_Event",             // 11
		"DTRK_TRUNK_CALL_PROC_REQ_Event",        // 12
		"DTRK_TRUNK_ALERT_REQ_Event",            // 13
		"DTRK_TRUNK_ANSWER_REQ_Event",           // 14
		"DTRK_TRUNK_DISCONNECT_REQ_Event",       // 15
		"DTRK_TRUNK_RELEASE_REQ_Event",          // 16
		"DTRK_TRUNK_RELEASE_RSP_Event",          // 17
		"DTRK_TRUNK_FLASH_REQ_Event",            // 18
		"DTRK_TRUNK_SEND_TONE_REQ_Event",        // 19
		"DTRK_TRUNK_START_DIGIT_COL_REQ_Event",  // 20
		"DTRK_TRUNK_STOP_DIGIT_COL_REQ_Event",   // 21
		"DTRK_TRUNK_TRANSIT_INFO_Event", 	  // 22
		"DTRK_TRUNK_NUMBER_COMPLETE_Event",      // 23
		/* Framer driver events */                  
		"DTRK_FRAMER_0_DETECT_Event",            // 24 (SLIST_TAG_FRAMER_DTRK)
		"DTRK_FRAMER_1_DETECT_Event",            // 25
		"DTRK_FRAMER_2_DETECT_Event",            // 26
		"DTRK_FRAMER_3_DETECT_Event",            // 27
		"DTRK_FRAMER_4_DETECT_Event",            // 28
		"DTRK_FRAMER_5_DETECT_Event",            // 29
		"DTRK_FRAMER_6_DETECT_Event",            // 30
		"DTRK_FRAMER_7_DETECT_Event",            // 31
		"DTRK_FRAMER_8_DETECT_Event",            // 32
		"DTRK_FRAMER_9_DETECT_Event",            // 33
		"DTRK_FRAMER_A_DETECT_Event",            // 34
		"DTRK_FRAMER_B_DETECT_Event",            // 35
		"DTRK_FRAMER_C_DETECT_Event",            // 36
		"DTRK_FRAMER_D_DETECT_Event",            // 37
		"DTRK_FRAMER_E_DETECT_Event",            // 38
		"DTRK_FRAMER_F_DETECT_Event",            // 39
		/* Alarm handler events */                  
		"DTRK_ALARM_Event",                      // 40 (SLIST_TAG_ALARM_DTRK)
		/* DSP driver events */
		"DTRK_DSP_DTMF_DETECT_Event",            // 41 (SLIST_TAG_DSP)
		"DTRK_DSP_BANKSWITCH_Event",             // 42
		"DTRK_DSP_TONE_DETECT_Event",            // 43
		"DTRK_DSP_CID_DETECT_Event",             // 44
		"DTRK_DSP_TONE_SENT_Event",              // 45
	FSM_ATTRIBUTE"EXTDR",
		"EXTDR_FLASH_PEND_TIMER_Event", // 0
		"EXTDR_RING_TIMER_Event",       // 1
		"EXTDR_RING_DEACTIVATE_Event",  // 2
		"EXTDR_RING_FILTER_Event",      // 3
		"EXTDR_DISCONNECT_TIMER_Event", // 4
		"EXTDR_CID_AS_TIMER_Event",     // 5
		"EXTDR_VMWI_TIMER_Event",       // 6
		"EXTDR_VMWI_REFRESH_TIMER_Event", // 7
		"EXTDR_EXT_ALERT_REQ_Event",    // 8
		"EXTDR_EXT_RELEASE_REQ_Event",  // 9
		"EXTDR_EXT_DIGIT_COL_ON_Event", // 10
		"EXTDR_EXT_DIGIT_COL_OFF_Event",// 11
		"EXTDR_EXT_SEND_TONE_Event",    // 12
		"EXTDR_EXT_DISCONNECT_REQ_Event",//13
		"EXTDR_EXT_RELEASE_CONNECTION_Event", //14
		"EXTDR_EXT_SPECIFIC_Event",     //15
		"EXTDR_EXT_ANSWER_REQ_Event",   //16
		"EXTDR_EXT_CALL_PROC_REQ_Event",//17
		"EXTDR_EXT_ALERT_RSP_REQ_Event",//18
		"EXTDR_EXT_UPDATE_VMWI_Event",  //19
		"EXTDR_QSLAC_OFFHOOK_Event",    //20
		"EXTDR_QSLAC_ONHOOK_Event",     //21
		"EXTDR_DSP_DTMF_DETECT_Event",  //22
		"EXTDR_DSP_BANKSWITCH_Event",   //23
		"EXTDR_DSP_TONE_DETECT_Event",  //24
		"EXTDR_DSP_CID_DETECT_Event",   //25
		"EXTDR_DSP_TONE_SENT_Event",    //26
		"EXTDR_DSP_CID_SENT_Event",     //27
		"EXTDR_DSP_DT_AS_SENT_Event",   //28 
		"EXTDR_DSP_VMWI_SENT_Event",    //29 
	FSM_ATTRIBUTE"HDRV",
		"HDRV_RING_TIMER_Event",              // 0
		"HDRV_DISCONNECT_Event",              // 1
		"HDRV_CALL_CHECK_Event",              // 2
		"HDRV_CALL_MAX_RESPONSE_TIME_Event",  // 3
		"HDRV_VPM_DTMF_Sent_Event",           // 4
		"HDRV_VPM_DTMF_Detected_Event",       // 5
		"HEXT_ALERT_REQ_Event",               // 6
		"HEXT_RELEASE_REQ_Event",             // 7
		"HEXT_DIGIT_COL_ON_Event",            // 8
		"HEXT_DIGIT_COL_OFF_Event",           // 9
		"HEXT_SEND_TONE_Event",               // 10
		"HEXT_DISCONNECT_REQ_Event",          // 11
		"HEXT_SPECIFIC_Event",                // 12
		"HEXT_ANSWER_REQ_Event",              // 13
		"HEXT_CALL_PROC_REQ_Event",           // 14
		"HEXT_ALERT_RSP_REQ_Event",           // 15
		"HEXT_SET_ID_REQ_Event",              // 16
		"HTRK_BLOCK_REQ_Event",               // 17
		"HTRK_UNBLOCK_REQ_Event",             // 18
		"HTRK_CALL_REQ_Event",                // 19
		"HTRK_INFO_REQ_Event",                // 20
		"HTRK_CALL_RSP_Event",                // 21
		"HTRK_CALL_PROC_REQ_Event",           // 22
		"HTRK_ALERT_REQ_Event",               // 23
		"HTRK_ANSWER_REQ_Event",              // 24
		"HTRK_DISCONNECT_REQ_Event",          // 25
		"HTRK_RELEASE_REQ_Event",             // 26
		"HTRK_RELEASE_RSP_Event",             // 27
		"HTRK_FLASH_REQ_Event",               // 28
		"HTRK_SEND_TONE_REQ_Event",           // 29
		"HTRK_START_DIGIT_COL_REQ_Event",     // 30
		"HTRK_STOP_DIGIT_COL_REQ_Event",      // 31
		"HTRK_TRANSIT_INFO_Event",            // 32
		"HTRK_NUMBER_COMPLETE_Event",         // 33
		"H323_CALL_IND_Event",                // 34
		"H323_RINGBACK_IND_Event",            // 35
		"H323_CONNECTED_IND_Event",           // 36
		"H323_USER_SIGNAL_IND_Event",         // 37
		"H323_CHECK_CALL_IND_Event",          // 38
		"H323_DISCONNECTED_IND_Event",        // 39
		"H323_ERROR_IND_Event",               // 40
		"HDRV_DSP_DTMF_DETECT_Event",         // 41
		"HDRV_DSP_BANKSWITCH_Event",          // 42
		"HDRV_DSP_TONE_DETECT_Event",         // 43
		"HDRV_DSP_CID_DETECT_Event",          // 44
		"HDRV_DSP_TONE_SENT_Event",           // 45
		"IPDRV_RX_SAL_MEDIA_UPDATE_Event",	  // 46
		"MM_TX_HDRV_REGISTER_ACK_Event",      // 47
		"MM_TX_HDRV_MEDIA_UPDATE_Event",      // 48
	FSM_ATTRIBUTE"IDRV",
		"IDRV_ENBLOC_TIMER_Event",
		"IDRV_CLEARING_TIMER_Event",

		"IDRV_TRUNK_BLOCK_REQ_Event",      // Line-blocking requested by WS
		"IDRV_TRUNK_UNBLOCK_REQ_Event",    // WS tries to remove blocking
		"IDRV_TRUNK_CALL_REQ_Event",       // OB call setup attempt
		"IDRV_TRUNK_INFO_REQ_Event",       // OB call related digits to be sent
		"IDRV_TRUNK_CALL_RSP_Event",       // IB call confirmed, digits expected
		"IDRV_TRUNK_CALL_PROC_REQ_Event",  // IB call confirmed - no (more) digits possible
		"IDRV_TRUNK_ALERT_REQ_Event",      // IB call end user alerted - no digits
		"IDRV_TRUNK_ANSWER_REQ_Event",     // IB call answered
		"IDRV_TRUNK_DISCONNECT_REQ_Event", // Call disconnect invitation by WS
		"IDRV_TRUNK_RELEASE_REQ_Event",    // Call release request by WS
		"IDRV_TRUNK_RELEASE_RSP_Event",    // Call release confirmed by WS
		"IDRV_TRUNK_FLASH_REQ_Event",      // Flash signal requested
		"IDRV_TRUNK_SEND_TONE_REQ_Event",
		"IDRV_TRUNK_START_DIGIT_COL_REQ_Event",
		"IDRV_TRUNK_STOP_DIGIT_COL_REQ_Event",
		"IDRV_TRUNK_TRANSIT_INFO_Event",
		"IDRV_TRUNK_NUMBER_COMPLETE_Event",
		"IDRV_TRUNK_SERVICE_REQ_Event",
		"IDRV_CALL_IN_Event",
		"IDRV_SETUPACK_IN_Event",
		"IDRV_DIGIT_IN_Event",
		"IDRV_CALL_PROC_IN_Event",
		"IDRV_ALERT_Event",
		"IDRV_CONNECT_Event",
		"IDRV_Default_DISCONNECT_IN_Event",
		"IDRV_Default_RELEASE_IN_Event",
		"IDRV_PROGRESS_IN_Event",
		"IDRV_ERR_IN_Event",
		"IDRV_TRANSIT_INFO_Event",
		"IDRV_FACILITY_CO_Event",
		"IDRV_BLOCK_IN_Event",
		"IDRV_UNBLOCK_IN_Event",
		/* DSP driver events */
		"IDRV_DSP_DTMF_DETECT_Event",            
		"IDRV_DSP_BANKSWITCH_Event",            
		"IDRV_DSP_TONE_DETECT_Event",            
		"IDRV_DSP_CID_DETECT_Event",           
		"IDRV_DSP_TONE_SENT_Event",
	FSM_ATTRIBUTE"RTRK",
		/* Own events */
		"RTRK_TIMER_0_Event",                    // 0 (SLIST_TAG_RTRK_RX)
		"RTRK_TIMER_1_Event",                    // 1 
		"RTRK_TIMER_2_Event",                    // 2 
		/* Trunk request events */
		"RTRK_TRUNK_BLOCK_REQ_Event",            // 3
		"RTRK_TRUNK_UNBLOCK_REQ_Event",          // 4
		"RTRK_TRUNK_CALL_REQ_Event",             // 5
		"RTRK_TRUNK_INFO_REQ_Event",             // 6
		"RTRK_TRUNK_CALL_RSP_Event",             // 7
		"RTRK_TRUNK_CALL_PROC_REQ_Event",        // 8
		"RTRK_TRUNK_ALERT_REQ_Event",            // 9
		"RTRK_TRUNK_ANSWER_REQ_Event",           // 10
		"RTRK_TRUNK_DISCONNECT_REQ_Event",       // 11
		"RTRK_TRUNK_RELEASE_REQ_Event",          // 12
		"RTRK_TRUNK_RELEASE_RSP_Event",          // 13
		"RTRK_TRUNK_FLASH_REQ_Event",            // 14
		"RTRK_TRUNK_SEND_TONE_REQ_Event",        // 15
		"RTRK_TRUNK_START_DIGIT_COL_REQ_Event",  // 16
		"RTRK_TRUNK_STOP_DIGIT_COL_REQ_Event",   // 17
		/* RPCL WAN-trunk events */                  
		"RTRK_RPCL_SEIZE_IND_Event",             // 18
		"RTRK_RPCL_SEIZE_CNF_Event",             // 19
		"RTRK_RPCL_IB_CALL_IND_Event",           // 20
		"RTRK_RPCL_OB_CALL_CNF_Event",           // 21
		"RTRK_RPCL_IB_STATE_IND_Event",          // 22
		"RTRK_RPCL_OB_STATE_IND_Event",          // 23
		"RTRK_RPCL_CALL_ANS_IND_Event",          // 24
		"RTRK_RPCL_CALL_ANS_CNF_Event",          // 25
		"RTRK_RPCL_CALL_TERM_IND_Event",         // 26
		"RTRK_RPCL_CALL_TERM_CNF_Event",         // 27
		"RTRK_RPCL_TRUNK_FREE_IND_Event",        // 28
		"RTRK_RPCL_TRUNK_DOWN_IND_Event",        // 29
		"RTRK_RPCL_TRUNK_UP_IND_Event",          // 30
		/* DSP driver events */
		"RTRK_DSP_DTMF_DETECT_Event",            // 31 (SLIST_TAG_DSP)
		"RTRK_DSP_BANKSWITCH_Event",             // 32
		"RTRK_DSP_TONE_DETECT_Event",            // 33
		"RTRK_DSP_CID_DETECT_Event",             // 34
		"RTRK_DSP_TONE_SENT_Event",              // 35
	FSM_ATTRIBUTE"PHR",
		"PHR_TIMER_TIMER_Event",               //0   SLIST_TAG_PHR
		"PHR_DONE_PLAYING_Event",
		"PHR_XC_CALLBACK_Event",
	FSM_ATTRIBUTE"RSERVER",
		"RSERVER_RECV_Event",        /* Activate receive message action    */
		"RSERVER_SEND_Event",        /* Activate send message action       */  
		"RSERVER_SIG_UP_Event",      /* Activate signal RSERVER up action    */ 
		"RSERVER_SIG_DOWN_Event",    /* Activate signal RSERVER down action  */
	FSM_ATTRIBUTE"CFA",
		"CFA_CM_ALERTING_RSP_Event",           //0   SLIST_TAG_CM_TX
		"CFA_CM_CALL_ANSWERED_Event",          //1
		"CFA_CM_CALL_PROCEEDING_Event",        //2
		"CFA_CM_CONNECT_REQ_Event",            //3
		"CFA_CM_CONNECT_CONFIRMED_Event",      //4
		"CFA_CM_DISCONNECT_REQ_Event",         //5
		"CFA_CM_FLASH_REQ_Event",              //6
		"CFA_CM_RELEASE_REQ_Event",            //7
		"CFA_CM_RELEASE_COMPLETE_REQ_Event",   //8
		"CFA_CM_SEND_DIGITS_Event",            //9
		"CFA_CM_START_DIGIT_COLLECT_Event",    //10
		"CFA_CM_STOP_DIGIT_COLLECT_Event",     //11
		"CFA_CM_PROGRESS_REQ_Event",           //12
	FSM_ATTRIBUTE"CFD",
		"CFD_CM_ALERTING_RSP_Event",           //0   SLIST_TAG_CM_TX
		"CFD_CM_CALL_ANSWERED_Event",          //1
		"CFD_CM_CALL_PROCEEDING_Event",        //2
		"CFD_CM_CONNECT_REQ_Event",            //3
		"CFD_CM_CONNECT_CONFIRMED_Event",      //4
		"CFD_CM_DISCONNECT_REQ_Event",         //5
		"CFD_CM_FLASH_REQ_Event",              //6
		"CFD_CM_RELEASE_REQ_Event",            //7
		"CFD_CM_RELEASE_COMPLETE_REQ_Event",   //8
		"CFD_CM_SEND_DIGITS_Event",            //9
		"CFD_CM_START_DIGIT_COLLECT_Event",    //10
		"CFD_CM_STOP_DIGIT_COLLECT_Event",     //11
		"CFD_CM_PROGRESS_REQ_Event",           //12
	FSM_ATTRIBUTE"MCID",
		"MCID_DISCONNECT_TIMER_Event",          //0   SLIST_TAG_MCID
		"MCID_CM_ALERTING_RSP_Event",           //1   SLIST_TAG_CM_TX
		"MCID_CM_CALL_ANSWERED_Event",          //2
		"MCID_CM_CALL_PROCEEDING_Event",        //3
		"MCID_CM_CONNECT_REQ_Event",            //4
		"MCID_CM_CONNECT_CONFIRMED_Event",      //5
		"MCID_CM_DISCONNECT_REQ_Event",         //6
		"MCID_CM_FLASH_REQ_Event",              //7
		"MCID_CM_RELEASE_REQ_Event",            //8
		"MCID_CM_RELEASE_COMPLETE_REQ_Event",   //9
		"MCID_CM_SEND_DIGITS_Event",            //10
		"MCID_CM_START_DIGIT_COLLECT_Event",    //11
		"MCID_CM_STOP_DIGIT_COLLECT_Event",     //12
		"MCID_CM_PROGRESS_REQ_Event",           //13
		"MCID_CM_MCID_REQ_Event",               //14  SLIST_TAG_SERVICE
		"MCID_CM_MCID_RSP_Event",
	FSM_ATTRIBUTE"SMTP",
		"SMTP_SEND_MAIL_Event",         //SLIST_TAG_CMON_SMTP_TX
	FSM_ATTRIBUTE"CLOG",
		"CMON_CLOG_OPEN_Event",         //SLIST_TAG_CMON_CLOG_TX
		"CMON_CLOG_READ_UAENTRY_Event",
		"CMON_CLOG_WRITE_ENTRY_Event",
		"CMON_CLOG_NEW_ACK_NO_Event",
		"CMON_CLOG_UA_ACK_NO_Event",
	FSM_ATTRIBUTE"CMON",
		"CMON_CA_TIMER_Event",               /* SLIST_TAG_CMON         */
		"CMON_CM_UPDATE_STATUS_Event",
		"CMON_CM_CALL_STATUS_Event",
		"TSPI_CMON_NEW_CONNECTION_Event",    /* SLIST_TAG_TSPI_CMON_TX */
		"TSPI_CMON_RECEIVED_PDU_Event",
		"TSPI_CMON_DISCONNECTION_Event",
		"CLOG_CMON_LAST_POINTER_Event",      /* SLIST_TAG_CLOG_CMON_TX */
		"CLOG_CMON_UAENTRY_BUF_Event",
		"CLOG_CMON_NO_UAENTRY_Event",
		"TSPO_CMON_REQ_DEVINFO_Event",       /* SLIST_TAG_TSPO_CMON_TX */
		"TSPO_CMON_SEND_ACK_Event",
	FSM_ATTRIBUTE"TSPI",
		"TSPI_START_TSPI_Event",      //start itself.
	FSM_ATTRIBUTE"TSPO",
		"TSPI_TSPO_NEW_CONNECTION_Event",          /* SLIST_TAG_TSPI_TSPO_TX 		*/
		"TSPI_TSPO_SEND_CA_PDU_Event",
		"TSPI_TSPO_DISCONNECTION_Event",
		"TSPI_TSPO_GetDevDir_Event",
		"SERVICE_TSPO_TRANSMIT_PDU_Event",			/* SLIST_TAG_SERVICE_TSPO_TX	 */
	FSM_ATTRIBUTE"UM",
		"UM_TIMER_TIMER_Event", 		   		/* SLIST_TAG_UM 	  	 		*/
		"UM_TSPI_UM_PACKET_Event", 			/* SLIST_TAG_TSPI_SERVICE_TX 	*/
		"UM_TSPI_DISCONNECT_REQ_Event",
		"UM_TSPI_CA_Event",
		"UM_CM_RESERVE_ENDPOINT_RSP_Event",  	/* SLIST_TAG_CM_EPMGR_RX 		*/
	FSM_ATTRIBUTE"VM",
		"VM_CM_ALERTING_RSP_Event",                /*0*/    /* SLIST_TAG_CM_TX */
		"VM_CM_CALL_ANSWERED_Event",               /*1*/ 
		"VM_CM_CALL_PROCEEDING_Event",             /*2*/
		"VM_CM_CONNECT_REQ_Event",                 /*3*/
		"VM_CM_CONNECT_CONFIRMED_Event",           /*4*/
		"VM_CM_DISCONNECT_REQ_Event",              /*5*/
		"VM_CM_FLASH_REQ_Event",                   /*6*/
		"VM_CM_RELEASE_REQ_Event",                 /*7*/
		"VM_CM_RELEASE_COMPLETE_REQ_Event",        /*8*/
		"VM_CM_SEND_DIGITS_Event",			        /*9*/
		"VM_CM_START_DIGIT_COLLECT_Event",         /*10*/
		"VM_CM_STOP_DIGIT_COLLECT_Event",          /*11*/
		"VM_CM_PROGRESS_REQ_Event",                /*12*/
		"VM_CM_FLASH_RSP_Event",					/*13*/
		"VM_CM_REPLACE_CALLID_Event",				/*14*/
		"VM_CM_REQUEST_RESERVE_Event",				/*15*/
		"VM_CM_REPLACE_FSM_Event",				    /*16*/
		"VM_CM_NUMBER_COMPLETE_Event",				/*17*/
		"VM_CM_CANCEL_ENDPOINT_RESERVATION_Event",	/*18*/
		"VM_CM_RER_IND_RSP_Event",                 /*19*/      /* SLIST_TAG_VM_CM */
		"PHR_DONE_STREAMING_Event",                /*20*/      /* SLIST_TAG_PHR_TX */
		"PHR_DONE_STREAMING_MSG_Event",            /*21*/
		"PHR_START_SESSION_Event",                 /*22*/
		"PHR_CLOSE_SESSION_Event",                 /*23*/
		"VM_RECORD_LEN_TIMER_Event",               /*24*/      /* SLIST_TAG_VM */		
		"VM_DIGIT_DELAY_TIMER_Event",              /*25*/
		"VM_NO_ACTIVITY_TIMER_Event",              /*26*/
		"VM_PLAY_MESSAGE_Event",                   /*27*/
		"VM_SEND_MSG_COUNT_Event",                 /*28*/
		"VM_TEST_Event",                           /*29*/
		"VM_DONE_STREAMING_Event",                 /*30*/
		"VVM_VM_PLAY_REQUEST_Event",               /*31*/	   /* SLIST_TAG_VVM_TX*/
		"VVM_VM_DELETE_REQUEST_Event",             /*32*/
		"VVM_VM_STOP_REQUEST_Event",               /*33*/
		"VM_CM_RESTART_EVent",                     /*34*/
		"UM_VM_PLAY_REQUEST_Event",                /*35*/	    /* SLIST_TAG_UM_TX */	
		"UM_VM_DELETE_REQUEST_Event",              /*36*/
		"UM_VM_STOP_REQUEST_Event",                /*37*/
	FSM_ATTRIBUTE"VVM",
		"VVM_TIMER_TIMER_Event", /* SLIST_TAG_VVM */
		"EXT_CM_MSG_CNT_Event",	/* SLIST_TAG_VM_VM_UTIL_TX */
		"VVM_CM_VVMPACKET_Event", 
		"EXT_CM_VVMPACKET_Event",
		"VVM_CM_LOGOFF_Event",
		"CM_RESERVE_ENDPOINT_RSP_Event",  /* SLIST_TAG_CM_EPMGR_RX */
	FSM_ATTRIBUTE"VPDRV",
		"VPDRV_NEW_CMD_Event",
		"VPDRV_CMD_SENT_Event",
		"VPDRV_REG_MSG_PEND_Event",
		"VPDRV_SIG_MSG_PEND_Event",
		"VPDRV_DTMF_Ch0_Timer_Event",
		"VPDRV_DTMF_Ch1_Timer_Event",
		"VPDRV_DTMF_Ch2_Timer_Event",
		"VPDRV_DTMF_Ch3_Timer_Event",
		"VPDRV_ToneGen_Ch0_Timer_Event",
		"VPDRV_ToneGen_Ch1_Timer_Event",
		"VPDRV_ToneGen_Ch2_Timer_Event",
		"VPDRV_ToneGen_Ch3_Timer_Event",
	FSM_ATTRIBUTE"VSCTL",
		"VSCTLPLAYBACK_TIMER_Event",
		"VSCTLPLAYBACK_REFILL_Event",
		"VSCTLRECORD_TIMER_Event",
		"VSCTLRECORD_FLUSH_TIMER_Event",
		"VSCTLCLOSE_SESSION_Event",
		"VSCTLCLOSE_FILE_Event",
		"VSCTLCREATE_FILE_Event",
		"VSCTLDELETE_FILE_Event",
	FSM_ATTRIBUTE"WAPI",
		"WAPI_START_WAPI_Event",      //start itself.
	FSM_ATTRIBUTE"WAPO",
		"WAPI_WAPO_NEW_CONNECTION_Event",          /* SLIST_TAG_WAPI_WAPO_TX 		*/
		"WAPI_WAPO_SEND_CA_PDU_Event",
		"WAPI_WAPO_DISCONNECTION_Event",
		"WAPI_WAPO_GetDevDir_Event",
		"SERVICE_WAPO_TRANSMIT_PDU_Event",			/* SLIST_TAG_SERVICE_WAPO_TX	 */
	FSM_ATTRIBUTE"DTP",
		"DTP_CA_TIMER_Event",
		"DTPUT_SWITCH_DOWN_Event",
		"DTP_USER_SEND_REQ_Event",
	FSM_ATTRIBUTE"DTPUT",
		"DTPUT_START_DTPUT_Event", 
	FSM_ATTRIBUTE"WSHB",
		"WSHB_HEART_BEAT_Event",
	FSM_ATTRIBUTE"CFG",
		"CFG_SET_ATTRIBUTE_Event",
	FSM_ATTRIBUTE"OAM",
		"OAM_MAIN_Event",
	FSM_ATTRIBUTE"SESM",
		"SESM_START_SESM_Event",
	FSM_ATTRIBUTE"SESU",
		"SESU_RCV_TSP_STOP_Event",
		"SESU_RCV_CFG_STOP_Event",
	FSM_ATTRIBUTE"TSPM",
		"TSPM_START_TSPM_Event",
	FSM_ATTRIBUTE"TSPU",
		"TSPU_CA_TIMER_Event",            /* SLIST_TAG_TSP        */
		"TSPU_SES_START_TSP_Event",       /* SLIST_TAG_SES_TX     */
		"TSPU_EXT_CALL_REQ_STATUS_Event", /* SLIST_TAG_EXT_TSP_TX */
		"TSPU_EXT_RING_IND_Event",
		"TSPU_EXT_CALL_REQ_CONF_Event",
		"TSPU_EXT_REMOTE_HANGUP_IND_Event",
		"TSPU_EXT_LOCAL_HANGUP_IND_Event",
		"TSPU_EXT_ALERT_REQ_Event",
		"TSPU_EXT_CALL_ACTIVE_IND_Event",
		"TSPU_EXT_ATTACH_CONF_Event",
		"TSPU_EXT_OFFHOOK_IND_Event",
		"TSPU_EXT_HOLD_IND_Event",
		"TSPU_EXT_CANCEL_HOLD_IND_Event",
		"TSPU_EXT_TRANSFER_IND_Event",
		"TSPU_EXT_FORWARD_IND_Event",
		"TSPU_EXT_CANCEL_FORWARD_IND_Event",
		"TSPU_EXT_PICKUP_IND_Event",
		"TSPU_EXT_CONFERENCE_IND_Event",
		"TSPU_EXT_CONSULT_IND_Event",
		"TSPU_EXT_CANCEL_CONSULT_Event",
		"TSPU_EXT_REPORT_STATUS_Event",
		"TSPU_EXT_VVMPACKET_Event",
		"TSPU_EXT_DTMF_Event",
		"TSPU_EXT_FLASH_Event",
		"TSPU_EXT_ATTACH_REJ_Event",
	FSM_ATTRIBUTE"XC",
		"XC_DTP_DATA_IND_Event",           // 0
		"XC_DTP_SWITCH_DOWN_Event",        // 1
		"XC_DTP_SWITCH_UP_Event",          // 2
		"XC_VPM_TONE_IND_Event",           // 3
		"XC_MM_RSP_IND_Event",             // 4
	FSM_ATTRIBUTE"H323",
		"H323_seliSelect_Event",
		"HDRV_CALL_REQ_Event",
		"HDRV_USER_SIGNAL_REQ_Event",
		"HDRV_CHECK_CALL_REQ_Event",
		"HDRV_DISCONNECT_REQ_Event",
		"HDRV_GK_REGISTER_Event",
		"HDRV_GK_UNREGISTER_Event",
		"HDRV_SET_IP_ADDRESS_Event",
		"HDRV_CONNECT_REQ_Event",
		"IPDRV_TX_SAL_ALERT_REQ_Event",
		"IPDRV_TX_SAL_MEDIA_UPDATE_Event",
	FSM_ATTRIBUTE"SIP",
		"SIP_seliSelect_Event",
		"HDRV_CALL_REQ_Event",
		"HDRV_USER_SIGNAL_REQ_Event",
		"HDRV_CHECK_CALL_REQ_Event",
		"HDRV_DISCONNECT_REQ_Event",
		"HDRV_GK_REGISTER_Event",
		"HDRV_GK_UNREGISTER_Event",
		"HDRV_SET_IP_ADDRESS_Event",
		"HDRV_CONNECT_REQ_Event",
		"IPDRV_TX_SAL_ALERT_REQ_Event",
		"IPDRV_TX_SAL_MEDIA_UPDATE_Event",
	FSM_ATTRIBUTE"YP",
		"YP_TIMER_TIMER_Event",              //0   SLIST_TAG_YP
		"YP_DTP_DATA_IND_Event",             // 1  SLIST_TAG_DTP_TX
		"YP_DTP_SWITCH_DOWN_Event",          // 2
		"YP_DTP_SWITCH_UP_Event",            // 3   

	LIST_END
};

#endif
